sylva.base.sylva_base.SYLVABase Class Reference
The base object for SYLVA project.
Public Member Functions
def __init__ (self, args)
Constructs the object.
def load (cls, filepath)
Load one object from a file (.json format)
def dump (self, filepath=None)
dump one object to a file (.json format)
def __setattr__ (self, attr_name, attr_value)
Override python build-in set attribute method.
def __getattr__ (self, attr_name)
Override python build-in get attribute method.
def __str__ (self)
Returns a string representation of the object.
def get_storage_form (self)
Get the storage form of this object.
def clean_store (cls, filepath=None)
Clean store file of this class.
Properties
storage_form = property(get_storage_form)
A dict object as the storage form of this object.
Private Attributes
_class
The name of the class, e.g Actor
_excluded_attributes
The name of the attributes to be excluded when storing.
Detailed Description
The base object for SYLVA project.
All objects are inherented from this object.
Use dict(obj) to convert a SYLVABase object to dictionary object for serialization (https://en.wikipedia.org/wiki/Serialization).
For de-serialization, use ** before the dictioary object.
Check dump_and_load.py for example.
Definition at line 32 of file sylva_base.py.
Constructor & Destructor Documentation
__init__()
def sylva.base.sylva_base.SYLVABase.__init__ (self, args)
Constructs the object.
Parameters
self The object
args The arguments
Definition at line 51 of file sylva_base.py.
    def __init__(self, *args):
        dict.__init__(self, *args)
        self._class = self.__class__.__name__
        self._excluded_attributes = []
Member Function Documentation
__getattr__()
def sylva.base.sylva_base.SYLVABase.__getattr__ (self, attr_name)
Override python build-in get attribute method.
Parameters
self The object
attr_name The attribute name
Returns
value of the attribute
Definition at line 122 of file sylva_base.py.
Referenced by sylva.misc.tcl_parser.Keywords.__getitem__(), and sylva.misc.exec.DictObject.__getitem__().
    def __getattr__(self, attr_name):
        return self.get(attr_name, None)
__setattr__()
def sylva.base.sylva_base.SYLVABase.__setattr__ (self, attr_name, attr_value)
Override python build-in set attribute method.
Parameters
self The object
attr_name The attribute name
attr_value The attribute value
Definition at line 111 of file sylva_base.py.
Referenced by sylva.misc.tcl_parser.Keywords.__init__(), sylva.misc.exec.DictObject.__init__(), and sylva.misc.exec.SYLVA.execute_define_constraint_and_optimization().
    def __setattr__(self, attr_name, attr_value):
        self[attr_name] = attr_value
__str__()
def sylva.base.sylva_base.SYLVABase.__str__ (self)
Returns a string representation of the object.
Parameters
self The object
Returns
String representation of the object.
Definition at line 132 of file sylva_base.py.
Referenced by sylva.code_generation.air.BassObject.__repr__(), and sylva.base.sylva_base.SYLVASVG.__repr__().
    def __str__(self):
        return str(self.store)
clean_store()
def sylva.base.sylva_base.SYLVABase.clean_store (cls, filepath = None)
Clean store file of this class.
Parameters
cls The class
filepath The file path
Definition at line 162 of file sylva_base.py.
    def clean_store(cls, filepath=None):
        if filepath is None:
            filepath = f'{cls.__name__}_store.json'
        try:
            os.remove(filepath)
        except OSError:
            pass
dump()
def sylva.base.sylva_base.SYLVABase.dump (self, filepath = None)
dump one object to a file (.json format)
Parameters
cls The class
filepath The file path
Returns
object in class cls
Definition at line 98 of file sylva_base.py.
References sylva.base.sylva_base.SYLVABase.storage_form.
Referenced by sylva.misc.exec.SYLVA.execute_dump().
    def dump(self, filepath=None):
        if filepath is None:
            filepath = f'{self.__class__.__name__}_store.json'
        with open(filepath, 'w+', encoding='utf-8') as fp:
            json.dump(self.storage_form, fp, indent=4)
get_storage_form()
def sylva.base.sylva_base.SYLVABase.get_storage_form (self)
Get the storage form of this object.
Parameters
self The object
Returns
A dict object as the storage form
Definition at line 142 of file sylva_base.py.
References sylva.base.sylva_base.SYLVABase._excluded_attributes.
    def get_storage_form(self):
        def include(kv):
            return kv[0] not in self._excluded_attributes
        return dict(filter(include, self.items()))
load()
def sylva.base.sylva_base.SYLVABase.load (cls, filepath)
Load one object from a file (.json format)
The return type is based on the _class attribute value.
Parameters
cls The class
filepath The file path
Returns
object in class cls
Definition at line 67 of file sylva_base.py.
Referenced by sylva.misc.exec.SYLVA.execute_load().
    def load(cls, filepath):
        # read json dict from file
        with open(filepath, 'r', encoding='utf-8') as fp: json_dict = json.load(fp)
        # pop _class attribute from dict
        cls_name = json_dict.pop('_class', 'SYLVABase')
        # obtain class type from global variables
        cls = globals()[cls_name]
        # pop _excluded_attributes from dict
        _excluded_attributes = json_dict.pop('_excluded_attributes', [])
        # construct new object
        result = cls(**json_dict)
        # add _excluded_attributes
        result._excluded_attributes = _excluded_attributes
        return result
Member Data Documentation
_class
SYLVABase._class [private]
The name of the class, e.g Actor
Definition at line 53 of file sylva_base.py.
_excluded_attributes
SYLVABase._excluded_attributes [private]
The name of the attributes to be excluded when storing.
Definition at line 54 of file sylva_base.py.
Referenced by sylva.base.sylva_base.SYLVABase.get_storage_form().
Property Documentation
storage_form
SYLVABase.storage_form = property(get_storage_form) [static]
A dict object as the storage form of this object.
Definition at line 152 of file sylva_base.py.
Referenced by sylva.base.sylva_base.SYLVABase.dump().
The documentation for this class was generated from the following file:
base/sylva_base.py