sylva.dse.dse Namespace Reference
Classes
class design_specification
class solver_option
class system_constraint
class system_model
class system_optimization_objective
Functions
def time_cost (start_time, end_time)
def one_search (dse, log)
def search_all (design, option, log=status_log(), critical_log=status_log())
def get_result_csv (search_result, file_name='', report_items=['search time', fimps, area, energy, latency, sample, interval)
Variables
string __author__ = 'Shuo Li <contact@shuol.li>'
string __version__ = '2014-09-23-10:41'
sc = system_constraint
soo = system_optimization_objective
Function Documentation
get_result_csv()
def sylva.dse.dse.get_result_csv (search_result, file_name = '', report_items = ['search time', fimps, area, energy, latency, sample, interval)
Definition at line 421 of file dse.py.
Referenced by sylva.dse.dse.search_all().
                                 'latency', 'sample interval']):
    msg = 'index'
    for m in report_items:
        msg += ',' + m
    msg += '\n'
    index = 0
    for one_schedule_result in search_result:
        for one_solution in one_schedule_result:
            if one_solution != {}:
                msg += str(index)
                index += 1
                for key in report_items:
                    msg += ',' + str(one_solution[key])
                msg += '\n'
    if file_name == '':
        return msg
    else:
        dataf = open(file_name, 'w+')
        dataf.write(msg)
        dataf.close()
one_search()
def sylva.dse.dse.one_search (dse, log)
Perform one search.

Returns

1. if a solution is found (True or False)
2. the solution
3. the search log
Definition at line 141 of file dse.py.
References sylva.dse.dse.search_all().
Referenced by sylva.dse.dse.search_all().
def one_search(dse, log):
    '''
    Perform one search.
    Returns
    1. if a solution is found (True or False)
    2. the solution
    3. the search log
    '''
    result = {}
    performance = {}
    start_time = time.time()
    if dse.solver.NextSolution():
        end_time = time.time()
        log += 'Found one solution after %s branches\n' \
            % dse.solver.Branches()
        log += ' search time : %f\n' % ((end_time - start_time) / 1000)
        log += ' FIMPs : %s\n' % len(dse.fimps)
        log += ' area : %s\n' % dse.area.Value()
        log += ' latency : %s\n' % dse.latency.Value()
        log += ' energy : %s\n' % dse.energy.Value()
        log += ' sample interval: %s' % dse.sample_interval.Value()
        log.update()
        result['start'] = [int(t.Value()) for t in dse.start]
        result['end'] = [int(t.Value()) for t in dse.end]
        result['input_end'] = [int(t.Value()) for t in dse.input_end]
        result['output_start'] = [int(t.Value()) for t in dse.output_start]
        result['buffer_end'] = [int(t.Value()) for t in dse.buffer_end]
        result['extra_buffer'] = [int(t.Value()) for t in dse.extra_buffer]
        result['fimp_types'] = [-1 for f in dse.fimps]
        result['search time'] = (end_time - start_time) / 1000
        result['fimps'] = len(dse.fimps)
        result['area'] = dse.area.Value()
        result['latency'] = dse.latency.Value()
        result['energy'] = dse.energy.Value()
        result['sample interval'] = dse.sample_interval.Value()
        for f in dse.fimps:
            fimp_type = 0
            for var in dse.fimp_selection_variable[f.index]:
                if int(var.Value()) == 1:
                    result['fimp_types'][f.index] = fimp_type
                fimp_type = fimp_type + 1
        return True, result # , log
    else:
        end_time = time.time()
        log += 'No solution found after %s branches\n' \
            % dse.solver.Branches()
        log += ' search time : %f\n' % ((end_time - start_time) / 1000)
        log.update()
    return False, result # , log
search_all()
def sylva.dse.dse.search_all (design, option, log = status_log(), critical_log = status_log())
Definition at line 207 of file dse.py.
References sylva.dse.dse.get_result_csv(), sylva.dse.dse.one_search(), sylva.examples.sdfg.sdfg, and sylva.dse.dse.time_cost().
Referenced by sylva.dse.dse.one_search().
               critical_log=status_log()):
    results = []
    if 'prepare constraints and optimization objectives':
        if 'prepare constraints':
            tmax = design.system.constraint.tmax
            rmax = design.system.constraint.rmax
            amax = design.system.constraint.amax
            emax = design.system.constraint.emax
            log += 'Constraints: \n'
            log += 'Maximum latency (T_{max}) is %s\n' % tmax
            log += 'Maximum sample interval (R_{max}) is %s\n' % rmax
            log += 'Maximum area (A_{max}) is %s\n' % amax
            log += 'Maximum energy consumption (E_{max}) is %s\n' % emax
            log.update()
        if 'prepare optimization objectives':
            KT = design.system.optimization_objective.kt
            KR = design.system.optimization_objective.kr
            KA = design.system.optimization_objective.ka
            KE = design.system.optimization_objective.ke
            log += 'Optimization objectives: \n'
            log += 'KA = %s\n' % KA
            log += 'KE = %s\n' % KE
            log += 'KT = %s\n' % KT
            log += 'KR = %s\n' % KR
            log.update()
    if 'prepare system SDF graph':
        sdf_actors = design.system.actors
        sdf_edges = design.system.edges
    # prepare CGRA
    cgra = design.cgra
    # prepare FIMP library
    fimp_lib = design.fimp_lib
    if 'prepare solver options':
        time_limit = option.time_limit
        solutions_per_schedule = option.solutions_per_schedule
        effort = option.effort
        dse_engine = option.dse_engine
    if 'create HSDF graph and schedule it':
        log += 'Converting system SDF graph to HSDF graph ... \n'
        start_time = time.time()
        (actors, edges) = sdf_to_hsdf((sdf_actors, sdf_edges))
        end_time = time.time()
        log += 'Done. ' + time_cost(start_time, end_time) + '\n'
        log += '%s actors, %s edges.' % (len(actors), len(edges))
        log.update()
        log += 'Generating load balanced SDF schedule ...\n'
        start_time = time.time()
        all_sch = all_schedules((sdf_actors, sdf_edges))
        search_schedules = int(float(effort) * len(all_sch) / 100)
        schedules = some_schedules((sdf_actors, sdf_edges), search_schedules)
        end_time = time.time()
        log += 'Done. ' + time_cost(start_time, end_time) + '\n'
        log += '%s schedules.\n' % len(schedules)
        for s in schedules:
            log += '%s \n' % s
        log.update()
    if 'search for each schedule':
        search_index = 0
        for schedule_index, one_schedule in enumerate(schedules):
            result = []
            log += 'Schedule %s: \n' % schedule_index
            critical_log.status = log.status
            log.update()
            fimps = assign_fimps(actors, one_schedule)
            log += 'Used FIMP instance space holders are generated. \n'
            for f in fimps:
                log += '\n %s\n Actors: %s\n' % (f, f.actors)
            log.update()
            log += 'Preparing CSOP'
            log.update()
            start_time = time.time()
            dse = dse_engine(actors, edges, fimp_lib, fimps,
                             time_limit=time_limit,
                             max_area=amax, max_energy=emax,
                             max_latency=tmax, max_sample_interval=rmax,
                             KA=KA, KE=KE, KT=KT, KR=KR)
            end_time = time.time()
            log += 'Done. ' + time_cost(start_time, end_time)
            log.update()
            log += 'Search %s ... \n' % search_index
            critical_log.status = log.status
            log.update()
            start_time = time.time()
            keep_searching, r = one_search(dse, log)
            end_time = time.time()
            log += ('Search %s is done. ' % search_index) \
                + time_cost(start_time, end_time) + '\n'
            critical_log.status = log.status
            log.update()
            if not solutions_per_schedule:
                while keep_searching == True:
                    result.append(r)
                    search_index += 1
                    log += 'Search %s ... \n' % search_index
                    critical_log.status = log.status
                    log.update()
                    start_time = time.time()
                    keep_searching, r = one_search(dse, log)
                    end_time = time.time()
                    if not keep_searching:
                        log += 'Search failed, time limit %s seconds. \n' % (time_limit / 1000)
                        critical_log.status = log.status
                    else:
                        log += 'Done. ' + time_cost(start_time, end_time) + '\n'
                        critical_log.status = log.status
                    log.update()
            else:
                while solutions_per_schedule > 0 and keep_searching == True:
                    result.append(r)
                    search_index += 1
                    log += 'Search %s ... \n' % search_index
                    critical_log.status = log.status
                    log.update()
                    start_time = time.time()
                    keep_searching, r = one_search(dse)
                    end_time = time.time()
                    if not keep_searching:
                        log += 'Search failed, time limit %s seconds. \n' % (time_limit / 1000)
                        critical_log.status = log.status
                    else:
                        log += 'Done. ' + time_cost(start_time, end_time) + '\n'
                        critical_log.status = log.status
                    log.update()
                    solutions_per_schedule -= 1
            dse.solver.EndSearch()
            if len(result) > 0:
                for r in result:
                    if r != {}:
                        fimp_instances = []
                        for f in dse.fimps:
                            used_fimp = fimp_lib[f.name][r['fimp_types'][f.index]].clone()
                            used_fimp.index = f.index
                            used_fimp.actors = []
                            fimp_instances.append(used_fimp)
                            for a in f.actors:
                                a.assign_to(used_fimp)
                                a.fimp_index = used_fimp.index
                        for a in dse.actors:
                            i = a.index
                            a.add_schedule(
                                start=r['start'][i],
                                buffer_end=r['buffer_end'][i])
                            a.fimp.extra_buffer = r['extra_buffer'][i]
                        schedule_keys = ['start', 'input_end', 'output_start',
                                         'end', 'buffer_end', 'fimp_index']
                        r['actors'] = [a.serialize(schedule_keys, include_base_actor=True) for a in actors]
                        r['edges'] = [e.serialize() for e in edges]
                        r['fimp_instances'] = [f.serialize() for f in fimp_instances]
                        for a in actors:
                            log += 'Actor: %s\nFIMP: %s\n' % (a, a.fimp)
                            log.update()
                            log += 'Schedule:\n' + a.schedule.__str__()
                            log.update()
                    else:
                        log += 'No schedule for the following FIMP assignment:\n%s'\
                            % one_schedule
                        critical_log.status = log.status
                        log.update()
            results.append(result)
    critical_log.update()
    return results, sdfg(actors, edges)
time_cost()
def sylva.dse.dse.time_cost (start_time, end_time)
Definition at line 52 of file dse.py.
Referenced by sylva.dse.dse.search_all().
def time_cost(start_time, end_time):
    return 'Time cost: %f seconds.' % ((end_time - start_time) / 1000)
Variable Documentation
__author__
string sylva.dse.dse.__author__ = 'Shuo Li <contact@shuol.li>' [private]
Definition at line 23 of file dse.py.
__version__
string sylva.dse.dse.__version__ = '2014-09-23-10:41' [private]
Definition at line 24 of file dse.py.
sc
sylva.dse.dse.sc = system_constraint
Definition at line 81 of file dse.py.
soo
sylva.dse.dse.soo = system_optimization_objective
Definition at line 96 of file dse.py.
Referenced by sylva.dse.dse.system_model.__init__().