sylva.code_generation.sylva_fimp_lib Namespace Reference
Classes
class method_collection
class template
Functions
def integer_vhdl (max_value, min_value=0)
def create_fsm_vhdl_template ()
def default_value (name, default_value_types=default_value_types)
def create_counter_FIMP_VHDL (actor)
def create_actor_control_FIMP_VHDL (actor, max_output=glic.IO)
def create_input_selector_FIMP_VHDL (actor, input_signal=glic.INPUT, io_signal=glic.IO, default_value_types=default_value_types, suffix='')
def create_output_selector_FIMP_VHDL (actor, output_signal=glic.INPUT, io_signal=glic.IO, default_value_types=default_value_types)
def create_fimp_control_FIMP_VHDL (actor, idle_signal=glic.IDLE)
def create_buffer_control_FIMP_VHDL (actor, output_signal=glic.OUTPUT, io_signal=glic.IO)
def create_output_buffer_FIMP_VHDL (actor)
Variables
list default_value_types
vhdl = method_collection()
fsm
counter
input_selector
output_selector
fimp_control
buffer_control
output_buffer
Function Documentation
create_actor_control_FIMP_VHDL()
def sylva.code_generation.sylva_fimp_lib.create_actor_control_FIMP_VHDL (actor, max_output = glic.IO)
Create actor control FSM FIMP in VHDL.

This VHDL entity only depends on IEEE.std_logic_1164 package.
Definition at line 81 of file sylva_fimp_lib.py.
References sylva.code_generation.sylva_fimp_lib.create_input_selector_FIMP_VHDL().
  def create_actor_control_FIMP_VHDL(actor, max_output = glic.IO):
    ''' Create actor control FSM FIMP in VHDL.
    This VHDL entity only depends on IEEE.std_logic_1164 package.
    '''
    control = actor.control
    attributes = {}
    attributes['libraries'] = {'IEEE' : ['std_logic_1164.all']}
    attributes['cycle_port'] = actor.input_ports[0]
    attributes['state_port'] = actor.output_ports[0]
    attributes['entity_name'] = actor.name
    attributes['control'] = control
    attributes['state_count'] = len(control.states)
    return jinja2Template(sylva_default_fimp.vhdl.fsm.code_template).render(attributes)
create_buffer_control_FIMP_VHDL()
def sylva.code_generation.sylva_fimp_lib.create_buffer_control_FIMP_VHDL (actor, output_signal = glic.OUTPUT, io_signal = glic.IO)
Create buffer control FIMP in VHDL.

This VHDL entity only depends on IEEE.std_logic_1164 package.
Definition at line 188 of file sylva_fimp_lib.py.
References sylva.misc.exec.type.
Referenced by sylva.code_generation.sylva_fimp_lib.create_fimp_control_FIMP_VHDL().
    output_signal = glic.OUTPUT, io_signal = glic.IO):
    ''' Create buffer control FIMP in VHDL.
    This VHDL entity only depends on IEEE.std_logic_1164 package.
    '''
    attributes = {}
    attributes['libraries'] = {'IEEE' : ['std_logic_1164.all']}
    attributes['entity_name'] = actor.name
    attributes['current_cycle_port'] = actor.current_cycle_port
    attributes['control_ports'] = \
      [ (control_port, actor.wr_ports[i]) for i, control_port in enumerate(actor.control_ports) ]
    # extra buffer is True
    if actor.address_ports == [] :
      attributes['address_ports'] = []
    else :
      if type(actor.address_ports[0]) is list :
        attributes['address_ports'] = [ p for ps in actor.address_ports for p in ps ]
      else :
        attributes['address_ports'] = actor.address_ports
    attributes['OUTPUT'] = output_signal
    attributes['IO'] = io_signal
    return jinja2Template(sylva_default_fimp.vhdl.buffer_control.code_template).render(attributes)
create_counter_FIMP_VHDL()
def sylva.code_generation.sylva_fimp_lib.create_counter_FIMP_VHDL (actor)
Create counter FIMP in VHDL.

This VHDL entity only depends on IEEE.std_logic_1164 package.
Definition at line 66 of file sylva_fimp_lib.py.
  def create_counter_FIMP_VHDL(actor):
    ''' Create counter FIMP in VHDL.
    This VHDL entity only depends on IEEE.std_logic_1164 package.
    '''
    attributes = {}
    attributes['libraries'] = {'IEEE' : ['std_logic_1164.all']}
    for a in dir(actor) :
      attributes[a] = getattr(actor, a)
    return jinja2Template(sylva_default_fimp.vhdl.counter.code_template).render(attributes)
create_fimp_control_FIMP_VHDL()
def sylva.code_generation.sylva_fimp_lib.create_fimp_control_FIMP_VHDL (actor, idle_signal = glic.IDLE)
Create FIMP control FIMP in VHDL.

This VHDL entity only depends on IEEE.std_logic_1164 package.
Definition at line 169 of file sylva_fimp_lib.py.
References sylva.code_generation.sylva_fimp_lib.create_buffer_control_FIMP_VHDL().
Referenced by sylva.code_generation.sylva_fimp_lib.create_output_selector_FIMP_VHDL().
    idle_signal = glic.IDLE):
    ''' Create FIMP control FIMP in VHDL.
    This VHDL entity only depends on IEEE.std_logic_1164 package.
    '''
    attributes = {}
    attributes['libraries'] = {'IEEE' : ['std_logic_1164.all']}
    attributes['entity_name'] = actor.name
    attributes['input_ports'] = actor.input_ports
    attributes['en_port'] = actor.output_ports[0]
    attributes['IDLE'] = idle_signal
    return jinja2Template(sylva_default_fimp.vhdl.fimp_control.code_template).render(attributes)
create_fsm_vhdl_template()
def sylva.code_generation.sylva_fimp_lib.create_fsm_vhdl_template ()
Definition at line 37 of file sylva_fimp_lib.py.
  def create_fsm_vhdl_template() :
    attribute_keys = [
      'control',
      'state_count',
      'entity_name',
      'libraries',
      'output_type_string',
      'input_type_string' ]
    import sylva_default_fimp.vhdl.fsm
    fsm_code_template = sylva_default_fimp.vhdl.fsm.code_template
    return template('VHDL', attribute_keys, fsm_code_template)
create_input_selector_FIMP_VHDL()
def sylva.code_generation.sylva_fimp_lib.create_input_selector_FIMP_VHDL (actor, input_signal = glic.INPUT, io_signal = glic.IO, default_value_types = default_value_types, suffix = '')
Definition at line 102 of file sylva_fimp_lib.py.
References sylva.code_generation.sylva_fimp_lib.create_output_selector_FIMP_VHDL(), and sylva.code_generation.sylva_fimp_lib.default_value().
Referenced by sylva.code_generation.sylva_fimp_lib.create_actor_control_FIMP_VHDL().
    suffix = ''):
    def control_map_object() : pass
    ''' Create input selector FIMP in VHDL.
    This VHDL entity only depends on IEEE.std_logic_1164 package.
    '''
    attributes = {}
    attributes['libraries'] = {'IEEE' : ['std_logic_1164.all']}
    for a in dir(actor) :
      attributes[a] = getattr(actor, a)
    for o in actor.output_ports :
      o.default = default_value(o.type.name)
    attributes['INPUT'] = input_signal
    attributes['IO'] = io_signal
    return jinja2Template(sylva_default_fimp.vhdl.input_selector.code_template).render(attributes)
create_output_buffer_FIMP_VHDL()
def sylva.code_generation.sylva_fimp_lib.create_output_buffer_FIMP_VHDL (actor)
Create output buffer FIMP in VHDL.

This VHDL entity only depends on IEEE.std_logic_1164 package.
Definition at line 216 of file sylva_fimp_lib.py.
References sylva.code_generation.sylva_fimp_lib.default_value().
  def create_output_buffer_FIMP_VHDL(actor):
    ''' Create output buffer FIMP in VHDL.
    This VHDL entity only depends on IEEE.std_logic_1164 package.
    '''
    attributes = {}
    attributes['libraries'] = {'IEEE' : ['std_logic_1164.all']}
    attributes['entity_name'] = actor.name
    attributes['buffer_size'] = actor.buffer_size
    attributes['wr_port'] = actor.wr_port
    attributes['write_address_port'] = actor.write_address_port
    attributes['read_address_port'] = actor.read_address_port
    attributes['data_input_port'] = actor.data_input_port
    attributes['data_output_port'] = actor.data_output_port
    attributes['default_data_output'] = default_value(actor.data_input_port.type.name)
    return jinja2Template(sylva_default_fimp.vhdl.output_buffer.code_template).render(attributes)
create_output_selector_FIMP_VHDL()
def sylva.code_generation.sylva_fimp_lib.create_output_selector_FIMP_VHDL (actor, output_signal = glic.INPUT, io_signal = glic.IO, default_value_types = default_value_types)
Create output selector FIMP in VHDL.

This VHDL entity only depends on IEEE.std_logic_1164 package.
Definition at line 127 of file sylva_fimp_lib.py.
References sylva.code_generation.sylva_fimp_lib.create_fimp_control_FIMP_VHDL(), and sylva.code_generation.sylva_fimp_lib.default_value().
Referenced by sylva.code_generation.sylva_fimp_lib.create_input_selector_FIMP_VHDL().
    default_value_types = default_value_types):
    ''' Create output selector FIMP in VHDL.
    This VHDL entity only depends on IEEE.std_logic_1164 package.
    '''
    attributes = {}
    attributes['libraries'] = {'IEEE' : ['std_logic_1164.all']}
    attributes['entity_name'] = actor.name
    control_ports = [ (actor.input_ports[i].name, actor.input_ports[i].type.name)
                      for i in actor.control_port_range ]
    attributes['control_ports'] = control_ports
    control_count = len(control_ports)
    data_input_ports = []
    for i in actor.data_port_range :
      pname = actor.input_ports[i + control_count].name
      ptype = actor.input_ports[i + control_count].type.name
      pvalue = default_value(actor.input_ports[i + control_count].type.name)
      data_input_ports.append((pname, ptype, pvalue))
    attributes['data_input_ports'] = data_input_ports
    data_output_ports = [(p.name, p.type.name, default_value(p.type.name)) for p in
      actor.output_ports]
    attributes['data_output_ports'] = data_output_ports
    data_input_ports_count = len(data_input_ports)
    data_input_ports_range = xrange(data_input_ports_count)
    control_map = [ (cp[0], [ (data_output_ports[j + i*data_input_ports_count], ip)
                               for j, ip in enumerate(data_input_ports) ])
                      for i, cp in enumerate(control_ports) ]
    attributes['control_map'] = control_map
    attributes['OUTPUT'] = output_signal
    attributes['IO'] = io_signal
    return jinja2Template(sylva_default_fimp.vhdl.output_selector.code_template).render(attributes)
default_value()
def sylva.code_generation.sylva_fimp_lib.default_value (name, default_value_types = default_value_types)
Definition at line 59 of file sylva_fimp_lib.py.
Referenced by sylva.code_generation.sylva_fimp_lib.create_input_selector_FIMP_VHDL(), sylva.code_generation.sylva_fimp_lib.create_output_buffer_FIMP_VHDL(), and sylva.code_generation.sylva_fimp_lib.create_output_selector_FIMP_VHDL().
  def default_value(name, default_value_types = default_value_types) :
    for d in default_value_types :
      if name.startswith(d[0]) :
        return d[1]
    return "'0'"
integer_vhdl()
def sylva.code_generation.sylva_fimp_lib.integer_vhdl (max_value, min_value = 0)
Definition at line 30 of file sylva_fimp_lib.py.
References sylva.examples.hsdfg.format.
def integer_vhdl(max_value, min_value = 0) :
  if max_value < min_value :
    max_value, min_value = min_value, max_value
  return 'integer range {0} to {1}'.format(min_value, max_value)
Variable Documentation
buffer_control
sylva.code_generation.sylva_fimp_lib.buffer_control
Definition at line 244 of file sylva_fimp_lib.py.
counter
sylva.code_generation.sylva_fimp_lib.counter
Definition at line 240 of file sylva_fimp_lib.py.
default_value_types
list sylva.code_generation.sylva_fimp_lib.default_value_types
Initial value:
= [
    ('std_logic_vector', "(others => '0')"),
    ('integer', 0) ]
Definition at line 55 of file sylva_fimp_lib.py.
fimp_control
sylva.code_generation.sylva_fimp_lib.fimp_control
Definition at line 243 of file sylva_fimp_lib.py.
fsm
sylva.code_generation.sylva_fimp_lib.fsm
Definition at line 239 of file sylva_fimp_lib.py.
input_selector
sylva.code_generation.sylva_fimp_lib.input_selector
Definition at line 241 of file sylva_fimp_lib.py.
output_buffer
sylva.code_generation.sylva_fimp_lib.output_buffer
Definition at line 245 of file sylva_fimp_lib.py.
output_selector
sylva.code_generation.sylva_fimp_lib.output_selector
Definition at line 242 of file sylva_fimp_lib.py.
vhdl
sylva.code_generation.sylva_fimp_lib.vhdl = method_collection()
Definition at line 238 of file sylva_fimp_lib.py.