sylva.misc.plot Namespace Reference
Classes
class point
class rectangle
Functions
def time_block (start, end, index, color='grey', height=0.2, subindex=1, subtotal=1, space=0.2)
def fimp_schedule_plot (fimps=[], height=0.2, plt=plt, input_color='green', output_color='pink', computation_color='grey', buffer_color='darkred')
def schedule_plot (actors=[], height=0.2, plt=plt, input_color='green', output_color='pink', computation_color='grey', buffer_color='darkred')
def fimp_execution_model_plot (fimps=[], height=0.2, plt=plt, input_color='green', output_color='pink', computation_color='grey', buffer_color='darkred')
def canvas_plot (rects, padding=0.1, rectangle_style=None, annotation_style=None, width=None, height=None, show_axis=True, show_ticks=False, plt=plt)
Variables
string __author__ = 'Shuo Li <contact@shuol.li>'
string __version__ = '2014-09-22-11:44'
dictionary default_rectangle_style
dictionary default_annotation_style
p = point(2, 2)
r = rectangle(4, 4, x = 0, y = 0)
Function Documentation
canvas_plot()
def sylva.misc.plot.canvas_plot (rects, padding = 0.1, rectangle_style = None, annotation_style = None, width = None, height = None, show_axis = True, show_ticks = False, plt = plt)
Definition at line 336 of file plot.py.
References sylva.misc.util.to_list().
Referenced by sylva.misc.plot.rectangle.place_below_of(), and sylva.base.cgra.cgra.plot().
    width = None, height = None, show_axis = True, show_ticks = False, plt = plt) :
    _rectangle_style = default_rectangle_style
    _rectangle_style.update(rectangle_style or {})
    _annotation_style = default_annotation_style
    _annotation_style.update(annotation_style or {})
    rects = to_list(rects)
    if not width :
      min_width = min([ rect.x for rect in rects ]) - padding
      max_width = max([ rect.x + rect.width for rect in rects ]) + padding
    else :
      min_width = 0
      max_width = width
    if not height :
      min_height = min([ rect.y for rect in rects ]) - padding
      max_height = max([ rect.y + rect.height for rect in rects ]) + padding
    else :
      min_height = 0
      max_height = height
    if show_axis :
      plt.axis([min_width, max_width, max_height, min_height])
      if show_ticks :
        plt.xticks(range(min_width, max_width+1))
        plt.yticks(range(min_height, max_height+1))
      else :
        plt.xticks(list(set([r.left.x for r in rects] \
          + [int(min_width), int(max_width)] + [r.right.x for r in rects])))
        plt.yticks(list(set([r.top.y for r in rects] \
          + [int(min_height), int(max_height)] + [r.bottom.y for r in rects])))
    else :
      plt.axis('off')
    plt.gca().set_aspect('equal')
    for rect in rects :
      plt.gca().add_patch(rect.get_patch())
      plt.gca().annotate(rect.name,
        (rect.x + 0.5 * rect.width, rect.y + 0.5 * rect.height),
        **_annotation_style)
    return plt
fimp_execution_model_plot()
def sylva.misc.plot.fimp_execution_model_plot (fimps = [], height = 0.2, plt = plt, input_color = 'green', output_color = 'pink', computation_color = 'grey', buffer_color = 'darkred')
Definition at line 103 of file plot.py.
References sylva.misc.plot.time_block().
Referenced by sylva.misc.plot.schedule_plot().
    buffer_color = 'darkred') :
    end_time = max(fimps, key = lambda f: f.computation_phase).computation_phase
    fimp_count = len(fimps)
    plt.axis([0, end_time + 2, 0, fimp_count + 2])
    plt.gca().grid(True)
    for i in xrange(len(fimps)) :
      input_block = time_block(start = 0,
        end = fimps[i].input_phase - 1,
        index = i,
        subindex = 0, subtotal = 3, color = input_color)
      computation_block = time_block(start = 0,
        end = fimps[i].computation_phase - 1,
        index = i,
        subindex = 1, subtotal = 3, color = computation_color)
      output_block = time_block(
        start = fimps[i].computation_phase - fimps[i].output_phase + 1,
        end = fimps[i].computation_phase - 1,
        index = i,
        subindex = 2, subtotal = 3, color = output_color)
      rx, ry = computation_block.get_xy()
      cx = rx + computation_block.get_width()/2.0
      cy = ry + computation_block.get_height()/2.0
      plt.gca().annotate(fimps[i], (cx, cy),
        color='black', weight='bold',
        fontsize=16, ha='center', va='center')
      plt.gca().add_patch(input_block)
      plt.gca().add_patch(output_block)
      plt.gca().add_patch(computation_block)
    return plt
fimp_schedule_plot()
def sylva.misc.plot.fimp_schedule_plot (fimps = [], height = 0.2, plt = plt, input_color = 'green', output_color = 'pink', computation_color = 'grey', buffer_color = 'darkred')
Definition at line 55 of file plot.py.
References sylva.misc.plot.schedule_plot().
Referenced by sylva.misc.plot.time_block().
    buffer_color = 'darkred') :
    actors = [ one_actor for one_fimp in fimps for one_actor in one_fimp.actors ]
    return schedule_plot(actors,
      height, plt,
      input_color, output_color, computation_color, buffer_color)
schedule_plot()
def sylva.misc.plot.schedule_plot (actors = [], height = 0.2, plt = plt, input_color = 'green', output_color = 'pink', computation_color = 'grey', buffer_color = 'darkred')
Definition at line 66 of file plot.py.
References sylva.misc.plot.fimp_execution_model_plot(), and sylva.misc.plot.time_block().
Referenced by sylva.misc.exec.SYLVA.execute_write_fimp_plots(), and sylva.misc.plot.fimp_schedule_plot().
    buffer_color = 'darkred') :
    end_time = max(actors, key = lambda n: n.buffer_end).buffer_end
    fimp_count = max(actors, key = lambda n: n.fimp.index).fimp.index
    plt.axis([0, end_time + 2, 0, (fimp_count + 2) * height *3])
    plt.gca().grid(True)
    for n in actors :
      input_block = time_block(n.start, n.input_end, n.fimp.index,
        subindex = 0, subtotal = 3, color = input_color)
      computation_block = time_block(n.start, n.end, n.fimp.index,
        subindex = 1, subtotal = 3, color = computation_color)
      output_block = time_block(n.output_start, n.end, n.fimp.index,
        subindex = 2, subtotal = 3, color = output_color)
      rx, ry = computation_block.get_xy()
      cx = rx + computation_block.get_width()/2.0
      cy = ry + computation_block.get_height()/2.0
      plt.gca().annotate('%s_%s' %(n.name, n.index), (cx, cy),
        color='black',
        # weight='bold',
        # fontsize=16,
        ha='center', va='center')
      plt.gca().add_patch(input_block)
      plt.gca().add_patch(output_block)
      if n.buffer_end > n.end:
        buffer_ext_block = time_block(n.end+1, n.buffer_end, n.fimp.index,
          subindex = 2, subtotal = 3, color = buffer_color)
        plt.gca().add_patch(buffer_ext_block)
      plt.gca().add_patch(computation_block)
    return plt
time_block()
def sylva.misc.plot.time_block (start, end, index, color = 'grey', height = 0.2, subindex = 1, subtotal = 1, space = 0.2)
Definition at line 37 of file plot.py.
References sylva.misc.plot.fimp_schedule_plot().
Referenced by sylva.misc.plot.fimp_execution_model_plot(), and sylva.misc.plot.schedule_plot().
    subindex = 1, subtotal = 1, space = 0.2) :
    total_height = height * subtotal
    x = start
    y = 0
    y = y + index * total_height
    y = y + space
    y = y + height * (subtotal - subindex - 1)
    return Rectangle((x, y), \
      width = end - start + 1, height = height, \
      facecolor = color, edgecolor = 'black', linestyle = 'solid')
Variable Documentation
__author__
string sylva.misc.plot.__author__ = 'Shuo Li <contact@shuol.li>' [private]
Definition at line 23 of file plot.py.
__version__
string sylva.misc.plot.__version__ = '2014-09-22-11:44' [private]
Definition at line 24 of file plot.py.
default_annotation_style
dictionary sylva.misc.plot.default_annotation_style
Initial value:
= {
    'color' : 'black',
    'fontweight' :'normal',
    'fontsize' : 12,
    'ha' : 'center',
    'va' : 'center'}
Definition at line 213 of file plot.py.
default_rectangle_style
dictionary sylva.misc.plot.default_rectangle_style
Initial value:
= {
    'facecolor' : 'white',
    'edgecolor' :'black',
    'linestyle' : 'solid',
    'linewidth' : 1,
    'width' : 0.4,
    'height' : 0.4,
    }
Definition at line 204 of file plot.py.
p
sylva.misc.plot.p = point(2, 2)
Definition at line 380 of file plot.py.
r
sylva.misc.plot.r = rectangle(4, 4, x = 0, y = 0)
Definition at line 381 of file plot.py.