sylva.misc.util Namespace Reference
Classes
class status_log
Functions
def chunks (l, n)
def all_files (path, ext_names=[])
def files_in_path (file_name, path)
def merge_dicts (a, b)
def to_list (a)
def min_items (values)
def max_items (values)
def min_items_with_floor (values, floor)
def max_items_with_ceil (values, ceil)
def min_index (values)
def max_index (values)
def evenly_pick (values, count)
def mkdir (new_dir)
def dir_and_file (provided_name)
Variables
string __author__ = 'Shuo Li <contact@shuol.li>'
string __version__ = '2015-08-15-23:20'
ceil = lambda x: int(math.ceil(x))
floor = lambda x: int(math.floor(x))
log = lambda x: math.log(x, 10)
log2 = lambda x: math.log(x, 2)
Function Documentation
all_files()
def sylva.misc.util.all_files (path, ext_names = [])
Definition at line 71 of file util.py.
References sylva.misc.util.to_list().
Referenced by sylva.frontend.simulink2sdf.simulink2sdf().
def all_files(path, ext_names=[]):
    path = to_list(path)
    result = []
    for p in path:
        result += [os.path.join(dirpath, filename)
                   for (dirpath, dirnames, filenames) in os.walk(p)
                   for filename in filenames]
    if not ext_names:
        return result
    ext_names = to_list(ext_names)
    return [f for f in result if os.path.splitext(f)[1] in ext_names]
chunks()
def sylva.misc.util.chunks (l, n)
Definition at line 67 of file util.py.
Referenced by sylva.misc.exec.SYLVA.execute_define_constraint_and_optimization().
def chunks(l, n):
    for i in range(0, len(l), n):
        yield l[i:i + n]
dir_and_file()
def sylva.misc.util.dir_and_file (provided_name)
Definition at line 135 of file util.py.
Referenced by sylva.misc.exec.clean_command(), sylva.misc.exec.SYLVA.execute_dump(), sylva.misc.exec.SYLVA.execute_generate(), sylva.misc.exec.SYLVA.execute_write_cgra_floorplans(), sylva.misc.exec.SYLVA.execute_write_fimp_plots(), and sylva.misc.exec.SYLVA.execute_write_hdl().
def dir_and_file(provided_name):
    if provided_name.startswith('./'):
        provided_name = provided_name[2:]
    name, ext = os.path.splitext(os.path.basename(provided_name))
    dirname = os.path.dirname(provided_name)
    # when provided_name is a dir
    if name == provided_name:
        name = ''
        dirname = provided_name
    if ext:
        output_dir = dirname
    elif name:
        output_dir = os.path.join(dirname, name)
    else:
        output_dir = dirname
    return output_dir, name, ext
evenly_pick()
def sylva.misc.util.evenly_pick (values, count)
Definition at line 123 of file util.py.
def evenly_pick(values, count):
    step = len(values) / (count - 1)
    mid = len(values) / 2
    return values[:mid:step] + values[-1:mid + 1:-step]
files_in_path()
def sylva.misc.util.files_in_path (file_name, path)
Definition at line 83 of file util.py.
References sylva.misc.util.to_list().
Referenced by sylva.misc.exec.SYLVA.execute_read_hdl(), and sylva.misc.exec.SYLVA.execute_set_attribute().
def files_in_path(file_name, path):
    paths = to_list(path)
    base_name = os.path.basename(file_name)
    result = [os.path.join(dirpath, filename)
              for path in paths
              for (dirpath, dirnames, filenames) in os.walk(path)
              for filename in filenames
              if filename == base_name]
    return result
max_index()
def sylva.misc.util.max_index (values)
Definition at line 120 of file util.py.
def max_index(values):
    return values.index(max(value))
max_items()
def sylva.misc.util.max_items (values)
Definition at line 106 of file util.py.
def max_items(values):
    return [(index, value) for index, value in enumerate(values) if value == max(values)]
max_items_with_ceil()
def sylva.misc.util.max_items_with_ceil (values, ceil)
Definition at line 113 of file util.py.
def max_items_with_ceil(values, ceil):
    return [(index, value) for index, value in enumerate(values)
            if value == max(values) and value < ceil]
merge_dicts()
def sylva.misc.util.merge_dicts (a, b)
Definition at line 93 of file util.py.
def merge_dicts(a, b):
    a.update(b)
    return a
min_index()
def sylva.misc.util.min_index (values)
Definition at line 117 of file util.py.
def min_index(values):
    return values.index(min(value))
min_items()
def sylva.misc.util.min_items (values)
Definition at line 103 of file util.py.
def min_items(values):
    return [(index, value) for index, value in enumerate(values) if value == min(values)]
min_items_with_floor()
def sylva.misc.util.min_items_with_floor (values, floor)
Definition at line 109 of file util.py.
def min_items_with_floor(values, floor):
    return [(index, value) for index, value in enumerate(values)
            if value == min(values) and value > floor]
mkdir()
def sylva.misc.util.mkdir (new_dir)
Definition at line 128 of file util.py.
Referenced by sylva.misc.exec.SYLVA.execute_dump(), sylva.misc.exec.SYLVA.execute_generate(), sylva.misc.exec.SYLVA.execute_write_cgra_floorplans(), sylva.misc.exec.SYLVA.execute_write_fimp_plots(), sylva.misc.exec.SYLVA.execute_write_hdl(), sylva.code_generation.floorplanner.floorplanner.plot_best_solution(), and sylva.code_generation.floorplanner.floorplanner.plot_solutions().
def mkdir(new_dir):
    try:
        if not os.path.exists(new_dir):
            os.mkdir(new_dir)
    except:
        pass
to_list()
def sylva.misc.util.to_list (a)
Definition at line 97 of file util.py.
Referenced by sylva.misc.util.all_files(), sylva.misc.plot.canvas_plot(), sylva.misc.vhdl_ulti.create_from_vhdl(), sylva.misc.util.files_in_path(), sylva.misc.exec.list_command(), and sylva.frontend.simulink2sdf.simulink2sdf().
def to_list(a):
    if isinstance(a, list):
        return a
    else:
        return [a]
Variable Documentation
__author__
string sylva.misc.util.__author__ = 'Shuo Li <contact@shuol.li>' [private]
Definition at line 23 of file util.py.
__version__
string sylva.misc.util.__version__ = '2015-08-15-23:20' [private]
Definition at line 24 of file util.py.
ceil
sylva.misc.util.ceil = lambda x: int(math.ceil(x))
Definition at line 157 of file util.py.
floor
sylva.misc.util.floor = lambda x: int(math.floor(x))
Definition at line 158 of file util.py.
log
sylva.misc.util.log = lambda x: math.log(x, 10)
Definition at line 159 of file util.py.
log2
sylva.misc.util.log2 = lambda x: math.log(x, 2)
Definition at line 160 of file util.py.