sylva.glic.glic Namespace Reference
Classes
class abb
class control
class edge
class state
Functions
def get_all_edges (hsdf_edges)
def merge_edges (edge_list)
def merge_two_edges (one_edge, another_edge)
def comp_edge (actor_a, port_a, actor_b, port_b)
def sorted_actor_port_list (actors, ports)
def merge_mega_edge_edge_src (one_smedge, one_edge)
def merge_mega_edge_edge_dest (one_smedge, one_edge)
def merge_mega_edge_src (one_smedge, another_smedge)
def merge_mega_edge_dest (one_smedge, another_smedge)
def merge_normal_edge (one_edge, another_edge)
def swap_edges (one_edge, another_edge, based_on)
def swap_edges_dest (one_edge, another_edge)
def swap_edges_src (one_edge, another_edge)
def create_output_buffer (one_output_port, buffer_size=None)
def create_output_buffers (one_fimp)
def create_actor_control (actor, INPUT=INPUT, COMPUTATION=COMPUTATION, OUTPUT=OUTPUT, IDLE=IDLE)
def create_actor_controls (one_fimp)
def create_input_selectors (one_fimp, all_edges, actor_controls)
def create_fimp_control (one_fimp, all_edges, actor_controls)
def create_output_selectors (one_fimp, all_edges, actor_controls)
def create_abb (one_fimp, all_edges)
Variables
string __author__ = 'Shuo Li <contact@shuol.li>'
string __version__ = '2014-09-23-10:43'
int IDLE = 0
int COMPUTATION = 1
int INPUT = 2
int OUTPUT = 4
int IO = INPUT + OUTPUT
Function Documentation
comp_edge()
def sylva.glic.glic.comp_edge (actor_a, port_a, actor_b, port_b)
Compare two (actor, port) pair based on actor index and port index

  actor_a.index > actor_b.index => 1
  actor_a.index == actor_b.index and port_a.index > port_b.index => 1
  actor_a.index == actor_b.index and port_a.index == port_b.index => 0
  otherwise -1
Definition at line 292 of file glic.py.
    def comp_edge((actor_a, port_a), (actor_b, port_b)):
        ''' Compare two (actor, port) pair based on actor index and port index
          actor_a.index > actor_b.index => 1
          actor_a.index == actor_b.index and port_a.index > port_b.index => 1
          actor_a.index == actor_b.index and port_a.index == port_b.index => 0
          otherwise -1
        '''
        if actor_a.index > actor_b.index:
            return 1
        if actor_a.index == actor_b.index:
            if port_a.index > port_b.index:
                return 1
            elif port_a.index == port_b.index:
                return 0
            else:
                return -1
create_abb()
def sylva.glic.glic.create_abb (one_fimp, all_edges)
Definition at line 806 of file glic.py.
References sylva.glic.glic.create_actor_controls(), sylva.glic.glic.create_fimp_control(), sylva.glic.glic.create_input_selectors(), sylva.glic.glic.create_output_buffers(), and sylva.glic.glic.create_output_selectors().
    def create_abb(one_fimp, all_edges):
        # generate all controls for all actors on this FIMP
        actor_controls \
            = create_actor_controls(one_fimp)
        # generate all input selector controls for all ports on this FIMP
        input_selector_controls \
            = create_input_selectors(one_fimp, all_edges, actor_controls)
        fimp_control \
            = create_fimp_control(one_fimp, all_edges, actor_controls)
        output_buffers \
            = create_output_buffers(one_fimp)
        output_selector_controls \
            = create_output_selectors(one_fimp, all_edges, actor_controls)
        return abb(one_fimp,
                   actor_controls,
                   input_selector_controls,
                   fimp_control,
                   output_buffers,
                   output_selector_controls)
create_actor_control()
def sylva.glic.glic.create_actor_control (actor, INPUT = INPUT, COMPUTATION = COMPUTATION, OUTPUT = OUTPUT, IDLE = IDLE)
Create control for one HSDF actor 
Definition at line 614 of file glic.py.
Referenced by sylva.glic.glic.create_actor_controls().
    def create_actor_control(actor, INPUT=INPUT, COMPUTATION=COMPUTATION,
      OUTPUT=OUTPUT, IDLE=IDLE):
        ''' Create control for one HSDF actor '''
        s = actor
        # Assume the states are INPUT, COMPUTATION, OUTPUT, IDLE
        states = [state(index=i) for i in range(4)]
        edges = [edge(source=states[i - 1],
                      destination=states[i])
                 for i in range(1, 4)]
        # [input]
        # [computation]
        # [output ]
        # if the output phase starts directly
        # first state should be INPUT + OUTPUT
        if actor.input_ports == []:
            states[0].output = COMPUTATION
        else:
            if s.output_start == 0:
                states[0].output = INPUT + OUTPUT
            else:
                states[0].output = INPUT
        # 0 1 2 3 4 5 6 7 8 9 10 11 schedule
        # [ input ]
        # [ output ]
        # 0 1 2 3 4 5 6 7 8 9 1011 12 clock cycles
        # [ S0 ][S1][S2 ][S3]
        # if input and output phases are not overlapping
        # we have one computation state then output states
        if s.input_end < s.output_start - 1:
            states[1].output = COMPUTATION
            states[2].output = OUTPUT
            states[3].output = IDLE
            # input -> compute
            edges[0].cycle = s.input_end + 1
            # compute -> output
            edges[1].cycle = s.output_start
            # output -> idle
            edges[2].cycle = s.end + 1
            # idle -> input
            # edges.append(edge(source = states[3],
            # destination = states[0],
            # cycle = 0))
        # 0 1 2 3 4 5 6 7 8 9 10 11 schedule
        # [ input ]
        # [ output ]
        # 0 1 2 3 4 5 6 7 8 9 1011 12 clock cycles
        elif s.input_end == s.output_start - 1:
            states[1].output = OUTPUT
            states[2].output = IDLE
            del states[3]
            del edges[2]
            # input -> output
            edges[0].cycle = s.input_end + 1
            # output -> idle
            edges[1].cycle = s.end + 1
            # idle -> input
            # edges.append(edge(source = states[2],
            # destination = states[0],
            # cycle = 0))
        # 0 1 2 3 4 5 6 7 8 9 10 11 schedule
        # [ input ]
        # [ output ]
        # 0 1 2 3 4 5 6 7 8 9 1011 12 clock cycles
        else:
            states[1].output = INPUT + OUTPUT
            states[2].output = OUTPUT
            states[3].output = IDLE
            # input -> input and output
            edges[0].cycle = s.output_start
            # input and output -> output
            edges[1].cycle = s.input_end + 1
            # output -> idle
            edges[2].cycle = s.end + 1
            # idle -> input
            # edges.append(edge(source = states[3],
            # destination = states[0],
            # cycle = 0))
        edges.append(edge(source=states[-1], destination=states[0], cycle=0))
        return control(states, edges, actor.index, default_state_index=len(states) - 1)
create_actor_controls()
def sylva.glic.glic.create_actor_controls (one_fimp)
  Generate all controls for all actors on this FIMP
Definition at line 704 of file glic.py.
References sylva.glic.glic.create_actor_control().
Referenced by sylva.glic.glic.create_abb().
    def create_actor_controls(one_fimp):
        '''
          Generate all controls for all actors on this FIMP
        '''
        return [create_actor_control(a) for a in one_fimp.actors]
create_fimp_control()
def sylva.glic.glic.create_fimp_control (one_fimp, all_edges, actor_controls)
  FIMP executes when
    bitwise OR on the outputs of all the actor controls != IDLE
Definition at line 743 of file glic.py.
Referenced by sylva.glic.glic.create_abb().
    def create_fimp_control(one_fimp, all_edges, actor_controls):
        '''
          FIMP executes when
            bitwise OR on the outputs of all the actor controls != IDLE
        '''
        states = []
        edges = []
        states.append(state(0, IDLE))
        states.append(state(1, COMPUTATION))
        edges.append(edge(states[0], states[1], '!=%s' % IDLE))
        edges.append(edge(states[1], states[0], '==%s' % IDLE))
        return control(states, edges, one_fimp)
create_input_selectors()
def sylva.glic.glic.create_input_selectors (one_fimp, all_edges, actor_controls)
  Each HSDF actor has its own control (cs).
  Each input port on the FIMP has its own input selector.

  Condition =
    bitwise OR on the outputs of all the actor controls
Definition at line 711 of file glic.py.
Referenced by sylva.glic.glic.create_abb().
    def create_input_selectors(one_fimp, all_edges, actor_controls):
        '''
          Each HSDF actor has its own control (cs).
          Each input port on the FIMP has its own input selector.
          Condition =
            bitwise OR on the outputs of all the actor controls
        '''
        output_ports = one_fimp.actors[0].input_ports
        input_selector_controls = []
        for op in output_ports:
            states = []
            edges = []
            states += [state(0, None)]
            for c in actor_controls:
                for s in c.states:
                    if s.output == INPUT or s.output == IO:
                        states.append(state(len(states), c.name))
                    else:
                        states.append(state(len(states), None))
                    edges.append(edge(states[-2], states[-1], s.output))
            edges[-1].destination = states[0]
            input_selector_controls.append(control(states, edges, op.name))
        return input_selector_controls
create_output_buffer()
def sylva.glic.glic.create_output_buffer (one_output_port, buffer_size = None)
  Create one output buffer for one output port in an HSDF actor.
Definition at line 583 of file glic.py.
Referenced by sylva.glic.glic.create_output_buffers().
    def create_output_buffer(one_output_port, buffer_size=None):
        '''
          Create one output buffer for one output port in an HSDF actor.
        '''
        if buffer_size == None:
            buffer_size = one_output_port.count
        if one_output_port != None:
            return {'port': one_output_port,
                    'buffer_size': buffer_size}
        return None
create_output_buffers()
def sylva.glic.glic.create_output_buffers (one_fimp)
  Create output buffers for one FIMP instance.
  Each port has its own buffer.
  If extra_buffer = 1,
    each actor has its own buffers for all its output ports.
Definition at line 597 of file glic.py.
References sylva.glic.glic.create_output_buffer().
Referenced by sylva.glic.glic.create_abb().
    def create_output_buffers(one_fimp):
        '''
          Create output buffers for one FIMP instance.
          Each port has its own buffer.
          If extra_buffer = 1,
            each actor has its own buffers for all its output ports.
        '''
        # one port one buffer
        # Consider all buffers are for the first HSDF actor on the FIMP
        if one_fimp.extra_buffer == 0:
            return [[create_output_buffer(p, buffer_size=len(one_fimp.actors) * p.count
      )
                     for p in one_fimp.actors[0].output_ports]]
        else:
            return [[create_output_buffer(p)
                     for p in a.output_ports]
                    for a in one_fimp.actors]
create_output_selectors()
def sylva.glic.glic.create_output_selectors (one_fimp, all_edges, actor_controls)
  Each HSDF actor has its own control (cs).
  Each output port on the FIMP has its own output selector.

  Condition =
    bitwise OR on the outputs of all the actor controls
Definition at line 758 of file glic.py.
Referenced by sylva.glic.glic.create_abb().
    def create_output_selectors(one_fimp, all_edges, actor_controls):
        '''
          Each HSDF actor has its own control (cs).
          Each output port on the FIMP has its own output selector.
          Condition =
            bitwise OR on the outputs of all the actor controls
        '''
        input_ports = one_fimp.actors[0].output_ports
        output_selector_controls = []
        for ip in input_ports:
            states = []
            edges = []
            states += [state(0, None)]
            for c in actor_controls:
                for s in c.states:
                    if s.output == OUTPUT or s.output == IO:
                        states.append(state(len(states), c.name))
                    else:
                        states.append(state(len(states), None))
                    edges.append(edge(states[-2], states[-1], s.output))
            edges[-1].destination = states[0]
            output_selector_controls.append(control(states, edges, ip.name))
        return output_selector_controls
get_all_edges()
def sylva.glic.glic.get_all_edges (hsdf_edges)
  Return all edges to be presented in the final implementation
Definition at line 196 of file glic.py.
References sylva.glic.glic.merge_edges().
def get_all_edges(hsdf_edges):
    '''
      Return all edges to be presented in the final implementation
    '''
    return merge_edges(hsdf_edges)
merge_edges()
def sylva.glic.glic.merge_edges (edge_list)
Recursively merge all HSDF edges 
Definition at line 205 of file glic.py.
References sylva.glic.glic.merge_two_edges().
Referenced by sylva.glic.glic.get_all_edges().
    def merge_edges(edge_list):
        ''' Recursively merge all HSDF edges '''
        with len(edge_list) as length:
            if length > 0:
                for i in xrange(length):
                    for j in xrange(length):
                        if i != j:
                            r = merge_two_edges(edge_list[i], edge_list[j])
                            if r != None:
                                edge_list[i] = r
                                del edge_list[j]
                                return merge_edges(edge_list)
        return edge_list
merge_mega_edge_dest()
def sylva.glic.glic.merge_mega_edge_dest (one_smedge, another_smedge)
  Merge two mega SDF edges
  with the same source actor and port
  when the destination actor and port are lists.
Definition at line 417 of file glic.py.
Referenced by sylva.glic.glic.merge_two_edges().
    def merge_mega_edge_dest(one_smedge, another_smedge):
        '''
          Merge two mega SDF edges
          with the same source actor and port
          when the destination actor and port are lists.
        '''
        if one_smedge.src_actor \
                == another_smedge.src_actor \
                and one_smedge.src_port \
                == another_smedge.src_port:
            result = sdf.edge()
            result.src_actor = one_smedge.src_actor
            result.src_port = one_smedge.src_port
            dest_actor = one_smedge.dest_actor + another_smedge.dest_actor
            dest_port = one_smedge.dest_port + another_smedge.dest_port
            list_to_sort = []
            for i in xrange(len(dest_actor)):
                list_to_sort.append((dest_actor[i], dest_port[i]))
            sorted_list = sorted(list_to_sort,
                                 key=functools.cmp_to_key(comp_edge))
            for i in xrange(len(sorted_list)):
                (dest_actor[i], dest_port[i]) = sorted_list[i]
            result.dest_actor = dest_actor
            result.dest_port = dest_port
            return result
        return None
merge_mega_edge_edge_dest()
def sylva.glic.glic.merge_mega_edge_edge_dest (one_smedge, one_edge)
  Merge one mega SDF edge with one SDF edge
  with the same source actor and port
  when the destination actor and port are lists.
Definition at line 355 of file glic.py.
References sylva.glic.glic.sorted_actor_port_list().
Referenced by sylva.glic.glic.merge_two_edges().
    def merge_mega_edge_edge_dest(one_smedge, one_edge):
        '''
          Merge one mega SDF edge with one SDF edge
          with the same source actor and port
          when the destination actor and port are lists.
        '''
        if one_smedge.src_actor \
                == one_edge.src_actor \
                and one_smedge.src_port \
                == one_edge.src_port:
            result = sdf.edge()
            result.src_actor = one_smedge.src_actor
            result.src_port = one_smedge.src_port
            dest_actor = one_smedge.dest_actor + [one_edge.dest_actor]
            dest_port = one_smedge.dest_port + [one_edge.dest_port]
            result.dest_actor, result.dest_port \
                = sorted_actor_port_list(dest_actor, dest_port)
            return result
        return None
merge_mega_edge_edge_src()
def sylva.glic.glic.merge_mega_edge_edge_src (one_smedge, one_edge)
  Merge one mega SDF edge with one SDF edge
  with the same destination actor and port
  when the source actor and port are lists.
Definition at line 329 of file glic.py.
References sylva.glic.glic.sorted_actor_port_list().
Referenced by sylva.glic.glic.merge_two_edges().
    def merge_mega_edge_edge_src(one_smedge, one_edge):
        '''
          Merge one mega SDF edge with one SDF edge
          with the same destination actor and port
          when the source actor and port are lists.
        '''
        if one_smedge.dest_actor \
                == one_edge.dest_actor \
                and one_smedge.dest_port \
                == one_edge.dest_port:
            result = sdf.edge()
            result.dest_actor = one_smedge.dest_actor
            result.dest_port = one_smedge.dest_port
            src_actor = one_smedge.src_actor + [one_edge.src_actor]
            src_port = one_smedge.src_port + [one_edge.src_port]
            result.src_actor, result.src_port \
                = sorted_actor_port_list(src_actor, src_port)
            return result
        return None
merge_mega_edge_src()
def sylva.glic.glic.merge_mega_edge_src (one_smedge, another_smedge)
  Merge two mega SDF edges
  with the same destination actor and port
  when the source actor and port are lists.
Definition at line 381 of file glic.py.
Referenced by sylva.glic.glic.merge_two_edges().
    def merge_mega_edge_src(one_smedge, another_smedge):
        '''
          Merge two mega SDF edges
          with the same destination actor and port
          when the source actor and port are lists.
        '''
        if one_smedge.dest_actor \
                == another_smedge.dest_actor \
                and one_smedge.dest_port \
                == another_smedge.dest_port:
            result = sdf.edge()
            result.dest_actor = one_smedge.dest_actor
            result.dest_port = one_smedge.dest_port
            src_actor = one_smedge.src_actor + another_smedge.src_actor
            src_port = one_smedge.src_port + another_smedge.src_port
            list_to_sort = []
            for i in xrange(len(src_actor)):
                list_to_sort.append((src_actor[i], src_port[i]))
            sorted_list = sorted(list_to_sort,
                                 key=functools.cmp_to_key(comp_edge))
            for i in xrange(len(sorted_list)):
                (src_actor[i], src_port[i]) = sorted_list[i]
            result.src_actor = src_actor
            result.src_port = src_port
            return result
        return None
merge_normal_edge()
def sylva.glic.glic.merge_normal_edge (one_edge, another_edge)
  Merge two normal SDF edges
  based on their source and destination.
Definition at line 453 of file glic.py.
References sylva.glic.glic.swap_edges().
Referenced by sylva.glic.glic.merge_two_edges().
    def merge_normal_edge(one_edge, another_edge):
        '''
          Merge two normal SDF edges
          based on their source and destination.
        '''
        # If two edge shares the same source actor and port,
        # merge the destination ports
        if one_edge.src_actor.index \
                == another_edge.src_actor.index \
                and one_edge.src_port.name \
                == another_edge.src_port.name:
            one_edge, another_edge \
                = swap_edges(one_edge, another_edge,
                             based_on='destination')
            result = sdf.edge()
            result.src_actor = one_edge.src_actor
            result.src_port = one_edge.src_port
            result.dest_actor = [one_edge.dest_actor,
                                 another_edge.dest_actor]
            result.dest_port = [one_edge.dest_port,
                                another_edge.dest_port]
            return result
        # If two edge shares the same destination actor and port,
        # merge the source ports
        if one_edge.dest_actor.index \
                == another_edge.dest_actor.index \
                and one_edge.dest_port.name \
                == another_edge.dest_port.name:
            one_edge, another_edge \
                = swap_edges(one_edge, another_edge,
                             based_on='source')
            result = sdf.edge()
            result.src_actor = [one_edge.src_actor,
                                another_edge.src_actor]
            result.src_port = [one_edge.src_port,
                               another_edge.src_port]
            result.dest_actor = one_edge.dest_actor
            result.dest_port = one_edge.dest_port
            return result
        return None
merge_two_edges()
def sylva.glic.glic.merge_two_edges (one_edge, another_edge)
Merge two SDF edges based on their source and destination 
Definition at line 222 of file glic.py.
References sylva.glic.glic.merge_mega_edge_dest(), sylva.glic.glic.merge_mega_edge_edge_dest(), sylva.glic.glic.merge_mega_edge_edge_src(), sylva.glic.glic.merge_mega_edge_src(), and sylva.glic.glic.merge_normal_edge().
Referenced by sylva.glic.glic.merge_edges().
    def merge_two_edges(one_edge, another_edge):
        ''' Merge two SDF edges based on their source and destination '''
        # edge : src_actor and dest_actor are actors
        # mega edge : src_actor or dest_actor is a list of actors
        if one_edge != another_edge:
            # edge, edge
            if isinstance(one_edge.src_actor, sdf.actor) \
                    and isinstance(another_edge.src_actor, sdf.actor) \
                    and isinstance(one_edge.dest_actor, sdf.actor) \
                    and isinstance(another_edge.dest_actor, sdf.actor):
                return merge_normal_edge(one_edge, another_edge)
            # mega edge, mega edge, destination is list
            if isinstance(one_edge.src_actor, sdf.actor) \
                    and isinstance(another_edge.src_actor, sdf.actor) \
                    and isinstance(one_edge.dest_actor, list) \
                    and isinstance(another_edge.dest_actor, list):
                return merge_mega_edge_dest(one_edge, another_edge)
            # mega edge, mega edge, source is list
            if isinstance(one_edge.src_actor, list) \
                    and isinstance(another_edge.src_actor, list) \
                    and isinstance(one_edge.dest_actor, sdf.actor) \
                    and isinstance(another_edge.dest_actor, sdf.actor):
                return merge_mega_edge_src(one_edge, another_edge)
            # mega edge, edge
            # source is list
            if isinstance(one_edge.src_actor, list) \
                    and isinstance(another_edge.src_actor, sdf.actor) \
                    and isinstance(one_edge.dest_actor, sdf.actor) \
                    and isinstance(another_edge.dest_actor, sdf.actor):
                return merge_mega_edge_edge_src(one_edge, another_edge)
            # mega edge, edge
            # destination is list
            if isinstance(one_edge.src_actor, sdf.actor) \
                    and isinstance(another_edge.src_actor, sdf.actor) \
                    and isinstance(one_edge.dest_actor, list) \
                    and isinstance(another_edge.dest_actor, sdf.actor):
                return merge_mega_edge_edge_dest(one_edge, another_edge)
            # edge, mega edge
            # source is list
            if isinstance(one_edge.src_actor, sdf.actor) \
                    and isinstance(another_edge.src_actor, list) \
                    and isinstance(one_edge.dest_actor, sdf.actor) \
                    and isinstance(another_edge.dest_actor, sdf.actor):
                return merge_mega_edge_edge_src(another_edge, one_edge)
            # edge, mega edge
            # destination is list
            if isinstance(one_edge.src_actor, sdf.actor) \
                    and isinstance(another_edge.src_actor, sdf.actor) \
                    and isinstance(one_edge.dest_actor, sdf.actor) \
                    and isinstance(another_edge.dest_actor, list):
                return merge_mega_edge_edge_dest(another_edge, one_edge)
        return None
sorted_actor_port_list()
def sylva.glic.glic.sorted_actor_port_list (actors, ports)
Definition at line 313 of file glic.py.
Referenced by sylva.glic.glic.merge_mega_edge_edge_dest(), and sylva.glic.glic.merge_mega_edge_edge_src().
    def sorted_actor_port_list(actors, ports):
        list_to_sort = [(actors[i], ports[i]) for i in xrange(len(actors))]
        sorted_list = sorted(list_to_sort,
                             key=functools.cmp_to_key(comp_edge))
        actor_result, port_result = [], []
        for i in xrange(len(sorted_list)):
            a, p = sorted_list[i]
            actor_result.append(a)
            port_result.append(p)
        return actor_result, port_result
swap_edges()
def sylva.glic.glic.swap_edges (one_edge, another_edge, based_on)
Definition at line 503 of file glic.py.
References sylva.glic.glic.swap_edges_dest(), and sylva.glic.glic.swap_edges_src().
Referenced by sylva.glic.glic.merge_normal_edge().
    def swap_edges(one_edge, another_edge, based_on):
        if based_on == 'source':
            return swap_edges_src(one_edge, another_edge)
        if based_on == 'destination':
            return swap_edges_dest(one_edge, another_edge)
swap_edges_dest()
def sylva.glic.glic.swap_edges_dest (one_edge, another_edge)
  Swap two edges to make sure that

  1. one_edge.dest_actor < another_edge.dest_actor
  or
  2. if one_edge.dest_actor == another_edge.dest_actor
     then one_edge.dest_port < another_edge.dest_port
Definition at line 509 of file glic.py.
Referenced by sylva.glic.glic.swap_edges().
    def swap_edges_dest(one_edge, another_edge):
        '''
          Swap two edges to make sure that
          1. one_edge.dest_actor < another_edge.dest_actor
          or
          2. if one_edge.dest_actor == another_edge.dest_actor
             then one_edge.dest_port < another_edge.dest_port
        '''
        # one_edge.dest_actor > another_edge.dest_actor
        # swap
        if one_edge.dest_actor.index \
                > another_edge.dest_actor.index:
            return another_edge, one_edge
        # one_edge.dest_actor == another_edge.dest_actor
        # and
        # one_edge.dest_port.index > another_edge.dest_port.index :
        # swap
        elif one_edge.dest_actor.index \
            == another_edge.dest_actor.index \
            and one_edge.dest_port.index \
                > another_edge.dest_port.index:
            return another_edge, one_edge
        # one_edge.dest_actor < another_edge.dest_actor
        # or
        # one_edge.dest_port.index < another_edge.dest_port.index
        # no touch
        else:
            return one_edge, another_edge
swap_edges_src()
def sylva.glic.glic.swap_edges_src (one_edge, another_edge)
  Swap two edges to make sure that

  1. one_edge.src_actor < another_edge.src_actor
  or
  2. if one_edge.src_actor == another_edge.src_actor
     then one_edge.src_port < another_edge.src_port
Definition at line 545 of file glic.py.
Referenced by sylva.glic.glic.swap_edges().
    def swap_edges_src(one_edge, another_edge):
        '''
          Swap two edges to make sure that
          1. one_edge.src_actor < another_edge.src_actor
          or
          2. if one_edge.src_actor == another_edge.src_actor
             then one_edge.src_port < another_edge.src_port
        '''
        # one_edge.src_actor > another_edge.src_actor
        # swap
        if one_edge.src_actor.index \
                > another_edge.src_actor.index:
            return another_edge, one_edge
        # one_edge.src_actor == another_edge.src_actor
        # and
        # one_edge.src_port.index > another_edge.src_port.index :
        # swap
        elif one_edge.src_actor.index \
            == another_edge.src_actor.index \
            and one_edge.src_port.index \
                > another_edge.src_port.index:
            return another_edge, one_edge
        # one_edge.dest_actor < another_edge.dest_actor
        # or
        # one_edge.dest_port.index < another_edge.dest_port.index
        # no touch
        else:
            return one_edge, another_edge
Variable Documentation
__author__
string sylva.glic.glic.__author__ = 'Shuo Li <contact@shuol.li>' [private]
Definition at line 23 of file glic.py.
__version__
string sylva.glic.glic.__version__ = '2014-09-23-10:43' [private]
Definition at line 24 of file glic.py.
COMPUTATION
int sylva.glic.glic.COMPUTATION = 1
Definition at line 41 of file glic.py.
IDLE
int sylva.glic.glic.IDLE = 0
Definition at line 40 of file glic.py.
INPUT
int sylva.glic.glic.INPUT = 2
Definition at line 42 of file glic.py.
IO
int sylva.glic.glic.IO = INPUT + OUTPUT
Definition at line 44 of file glic.py.
OUTPUT
int sylva.glic.glic.OUTPUT = 4
Definition at line 43 of file glic.py.