sylva.frontend.mdl_reader Namespace Reference
Classes
class simulink_model
class simulink_system
Functions
def get_string (one_string)
def get_list (one_list)
def get_block (one_block)
def get_value (one_value)
def get_model_name (value)
def get_block_defaults (block_defaults)
def get_one_block (block)
def get_system_block (block)
def get_system (value)
def processNode (tokens)
def read_type_count (type_count)
def record_port (block, port_index, port_name, token_type, token_size, token_count, io='in')
def read_mdl_lib_as_dict (mdl_path)
def read_mdl_model (mdl_path)
Variables
bool use_white_list = True
list property_list
level
ParsedModel = simulink_model()
key_value = Forward()
key = Word (alphanums + '$+-_*\\.')
value = Forward()
off = Keyword('off')
on = Keyword('on')
string_value = quotedString
other_value = Word (alphanums + '$+-_*\\.')
normal_value = on | off | string_value | other_value
block_block = nestedExpr('{', '}', content = key_value)
list_block = nestedExpr('[', ']', content = value)
parser = OneOrMore(key_value)
Function Documentation
get_block()
def sylva.frontend.mdl_reader.get_block (one_block)
Definition at line 62 of file mdl_reader.py.
References sylva.frontend.mdl_reader.get_value().
Referenced by sylva.frontend.mdl_reader.get_value().
  def get_block(one_block) :
    if isinstance(one_block, list) :
      result = {}
      for item in one_block :
        if not use_white_list or (item[0] in property_list) :
          result[ item[0] ] = get_value(item[1])
      return result
    else :
      return 'ERROR, value is not list but %s'\
              % one_block
get_block_defaults()
def sylva.frontend.mdl_reader.get_block_defaults (block_defaults)
Definition at line 90 of file mdl_reader.py.
References sylva.frontend.mdl_reader.get_one_block().
Referenced by sylva.frontend.mdl_reader.processNode().
  def get_block_defaults(block_defaults) :
    return [ get_one_block(block)
             for block in block_defaults ]
get_list()
def sylva.frontend.mdl_reader.get_list (one_list)
Definition at line 51 of file mdl_reader.py.
References sylva.frontend.mdl_reader.get_string().
Referenced by sylva.frontend.mdl_reader.get_value().
  def get_list(one_list) :
    if isinstance(one_list, list) :
      if len(one_list) == 1 :
        return [ get_string(one_list[0]) ]
      else :
        return [ item for item in one_list if item != ',' ]
      return one_list
    else :
      return 'ERROR, value is not list but %s'\
             % one_list
get_model_name()
def sylva.frontend.mdl_reader.get_model_name (value)
Definition at line 87 of file mdl_reader.py.
References sylva.frontend.mdl_reader.get_value().
Referenced by sylva.frontend.mdl_reader.processNode().
  def get_model_name(value) :
    return get_value(value)
get_one_block()
def sylva.frontend.mdl_reader.get_one_block (block)
Definition at line 95 of file mdl_reader.py.
References sylva.frontend.mdl_reader.get_value().
Referenced by sylva.frontend.mdl_reader.get_block_defaults().
  def get_one_block(block) :
    return [ (item[0], get_value(item[1]))
             for item in block[1]
               if not use_white_list or (item[0] in property_list) ]
get_string()
def sylva.frontend.mdl_reader.get_string (one_string)
Definition at line 42 of file mdl_reader.py.
Referenced by sylva.frontend.mdl_reader.get_list(), and sylva.frontend.mdl_reader.get_value().
  def get_string(one_string) :
    if isinstance(one_string, str) :
      if one_string.startswith('"') :
        one_string = one_string[1:-1]
      return one_string
    else :
      return 'ERROR, value is not string but %s'\
             % one_string
get_system()
def sylva.frontend.mdl_reader.get_system (value)
Definition at line 110 of file mdl_reader.py.
References sylva.frontend.mdl_reader.get_system_block(), and sylva.frontend.mdl_reader.get_value().
Referenced by sylva.frontend.mdl_reader.get_system_block(), and sylva.frontend.mdl_reader.processNode().
  def get_system(value):
    system = simulink_system()
    system.name = get_value(value[0][1])
    system.blocks = [ get_system_block(item[1])
                      for item in value
                        if item[0] == 'Block' ]
    system.lines = [ get_system_block(item[1])
                      for item in value
                        if item[0] == 'Line' ]
    return system
get_system_block()
def sylva.frontend.mdl_reader.get_system_block (block)
Definition at line 100 of file mdl_reader.py.
References sylva.frontend.mdl_reader.get_system(), and sylva.frontend.mdl_reader.get_value().
Referenced by sylva.frontend.mdl_reader.get_system().
  def get_system_block(block) :
    properties = {}
    for item in block :
      if isinstance(item[0], str) and (not use_white_list or (item[0] in property_list)) :
        if item[0] == 'System' :
          properties[item[0]] = get_system(item[1])
        else :
          properties[item[0]] = get_value(item[1])
    return properties
get_value()
def sylva.frontend.mdl_reader.get_value (one_value)
Definition at line 73 of file mdl_reader.py.
References sylva.frontend.mdl_reader.get_block(), sylva.frontend.mdl_reader.get_list(), and sylva.frontend.mdl_reader.get_string().
Referenced by sylva.frontend.mdl_reader.get_block(), sylva.frontend.mdl_reader.get_model_name(), sylva.frontend.mdl_reader.get_one_block(), sylva.frontend.mdl_reader.get_system(), and sylva.frontend.mdl_reader.get_system_block().
  def get_value(one_value) :
    if isinstance(one_value, str) :
      return get_string(one_value)
    elif isinstance(one_value, list) :
      if ',' in one_value :
        return get_list(one_value)
      elif len(one_value) == 1 :
        return get_value(one_value[0])
      else :
        return get_block(one_value)
    else :
      return 'ERROR, value is not string or list but %s'\
              % one_value
processNode()
def sylva.frontend.mdl_reader.processNode (tokens)
Definition at line 121 of file mdl_reader.py.
References sylva.frontend.mdl_reader.get_block_defaults(), sylva.frontend.mdl_reader.get_model_name(), and sylva.frontend.mdl_reader.get_system().
  def processNode(tokens):
    key, value = tokens[0].asList()
    # tokens[0] is for compensates the one additional [] level.
    global level
    global ParsedModel
    # read ParsedModel name
    if level == 0 and key == 'Name' :
      ParsedModel.name = get_model_name(value)
      level += 1
    elif level == 1 :
      # read block default parameters
      if key == 'BlockParameterDefaults' :
        ParsedModel.block_defaults = get_block_defaults(value)
      if key == 'System' :
        ParsedModel.system = get_system(value)
read_mdl_lib_as_dict()
def sylva.frontend.mdl_reader.read_mdl_lib_as_dict (mdl_path)
Definition at line 202 of file mdl_reader.py.
References sylva.frontend.mdl_reader.read_type_count(), and sylva.frontend.mdl_reader.record_port().
def read_mdl_lib_as_dict(mdl_path) :
  global ParsedModel
  p = parser.parseFile(mdl_path, True)
  if p[0][0] != 'Library' :
    print 'Input file is NOT a library (.mdl) but a %s' % p[0][0]
  lib = {}
  inport_index = 0
  outport_index = 1
  for func in ParsedModel.system.blocks :
    name = '%s/%s' % (ParsedModel.system.name, func['Name'])
    lib[ name ] = {}
    lib[ name ]['input_ports'] = {}
    lib[ name ]['output_ports'] = {}
    system = func['System']
    inport_index = 0
    outport_index = 0
    for port in system.blocks :
      if port['BlockType'] == 'Inport' :
        port_name, type_count = port['Name'].split(':')
        port_name.replace(' ', '')
        token_type, token_size, token_count \
        = read_type_count(type_count)
        lib[ name ], inport_index \
        = record_port(lib[ name ], inport_index,
            port_name, token_type, token_size, token_count,
            io = 'in')
      elif port['BlockType'] == 'Outport' :
        port_name, type_count = port['Name'].split(':')
        port_name.replace(' ', '')
        token_type, token_size, token_count \
        = read_type_count(type_count)
        lib[ name ], outport_index \
        = record_port(lib[ name ], outport_index,
            port_name, token_type, token_size, token_count,
            io = 'out')
  return lib
read_mdl_model()
def sylva.frontend.mdl_reader.read_mdl_model (mdl_path)
Definition at line 254 of file mdl_reader.py.
def read_mdl_model(mdl_path) :
  global ParsedModel
  p = parser.parseFile(mdl_path, True)
  if p[0][0] != 'Model' :
    print 'Input file is NOT a ParsedModel (.mdl) but a %s' % p[0][0]
  return copy.deepcopy(ParsedModel)
read_type_count()
def sylva.frontend.mdl_reader.read_type_count (type_count)
Definition at line 168 of file mdl_reader.py.
References sylva.frontend.mdl_reader.record_port().
Referenced by sylva.frontend.mdl_reader.read_mdl_lib_as_dict().
  def read_type_count(type_count) :
    type_count = type_count.lower()
    token_type = 'No type'
    token_size = 1
    token_count = 1
    port_properties = type_count.split(',')
    for p in port_properties :
      key, value = p.split('=')
      key = key.strip()
      value = value.strip()
      if key == 'type' :
        token_type = value
      elif key == 'size' :
        token_size = int(value)
      elif key == 'count' :
        token_count = int(value)
    return token_type, token_size, token_count
record_port()
def sylva.frontend.mdl_reader.record_port (block, port_index, port_name, token_type, token_size, token_count, io = 'in')
Definition at line 190 of file mdl_reader.py.
Referenced by sylva.frontend.mdl_reader.read_mdl_lib_as_dict(), and sylva.frontend.mdl_reader.read_type_count().
    token_type, token_size, token_count, io = 'in') :
    io += 'put_ports'
    block[io][port_index] = {}
    block[io][port_index]['name'] = port_name
    block[io][port_index]['token type'] = token_type
    block[io][port_index]['token size'] = token_size
    block[io][port_index]['token count'] = token_count
    return block, port_index + 1
Variable Documentation
block_block
sylva.frontend.mdl_reader.block_block = nestedExpr('{', '}', content = key_value)
Definition at line 158 of file mdl_reader.py.
key
sylva.frontend.mdl_reader.key = Word (alphanums + '$+-_*\\.')
Definition at line 147 of file mdl_reader.py.
key_value
sylva.frontend.mdl_reader.key_value = Forward()
Definition at line 144 of file mdl_reader.py.
level
sylva.frontend.mdl_reader.level
Definition at line 39 of file mdl_reader.py.
list_block
sylva.frontend.mdl_reader.list_block = nestedExpr('[', ']', content = value)
Definition at line 160 of file mdl_reader.py.
normal_value
sylva.frontend.mdl_reader.normal_value = on | off | string_value | other_value
Definition at line 156 of file mdl_reader.py.
off
sylva.frontend.mdl_reader.off = Keyword('off')
Definition at line 152 of file mdl_reader.py.
on
sylva.frontend.mdl_reader.on = Keyword('on')
Definition at line 153 of file mdl_reader.py.
other_value
sylva.frontend.mdl_reader.other_value = Word (alphanums + '$+-_*\\.')
Definition at line 155 of file mdl_reader.py.
ParsedModel
sylva.frontend.mdl_reader.ParsedModel = simulink_model()
Definition at line 40 of file mdl_reader.py.
parser
sylva.frontend.mdl_reader.parser = OneOrMore(key_value)
Definition at line 166 of file mdl_reader.py.
property_list
list sylva.frontend.mdl_reader.property_list
Initial value:
= [
  'BlockType',
  'SourceBlock',
  'System',
  'Block',
  'Ports',
  'Port',
  'PortNumber',
  'SampleTime',
  'SignalType',
  'SamplingMode',
  'Inputs',
  'Operator',
  'OutDataTypeStr',
  'Name',
  'SID',
  'SrcBlock',
  'SrcPort',
  'DstBlock',
  'DstPort']
Definition at line 6 of file mdl_reader.py.
string_value
sylva.frontend.mdl_reader.string_value = quotedString
Definition at line 154 of file mdl_reader.py.
use_white_list
bool sylva.frontend.mdl_reader.use_white_list = True
Definition at line 4 of file mdl_reader.py.
value
sylva.frontend.mdl_reader.value = Forward()
Definition at line 150 of file mdl_reader.py.