sylva.code_generation.mit_license Namespace Reference
Functions
def get_contact (year=year, authors=authors)
def get_wrapped_text (lic_title=lic_title, contact=get_contact(year, authors), permission=permission, permission_extra=permission_extra, final=final, width=80, comment_perfix='#', indention_size=2)
def vhdl (year=year, authors=authors, width=width, indention_size=vhdl_indention_size)
def python (year=year, authors=authors, width=width, indention_size=python_indention_size)
Variables
string __author__ = 'Shuo Li <contact@shuol.li>'
string __version__ = '2014-06-12-11:43'
year = time.strftime('%Y', time.localtime())
list authors = [ {'name': 'Shuo Li', 'email': 'contact@shuo.li'} ]
int width = 80
int vhdl_indention_size = 3
int python_indention_size = 2
string lic_title = 'The MIT License (MIT)'
string permission = 'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the `Software`), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:'
string permission_extra = 'The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.'
string final = 'THE SOFTWARE IS PROVIDED `AS IS`, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.'
Function Documentation
get_contact()
def sylva.code_generation.mit_license.get_contact (year = year, authors = authors)
Generate the 'contact' part of the license body.

  year
    integer, e.g. 2014

  authors
    authors with their emails
    e.g.
    [
      { 'name' : 'one author',
        'email' : 'one@author.com' }
      { 'name' : 'another author',
        'email' : 'another@author.com' }
    ]
Definition at line 47 of file mit_license.py.
References sylva.code_generation.mit_license.get_wrapped_text().
Referenced by sylva.code_generation.mit_license.python(), and sylva.code_generation.mit_license.vhdl().
def get_contact(year = year, authors = authors) :
  '''Generate the 'contact' part of the license body.
    year
      integer, e.g. 2014
    authors
      authors with their emails
      e.g.
      [
        { 'name' : 'one author',
          'email' : 'one@author.com' }
        { 'name' : 'another author',
          'email' : 'another@author.com' }
      ]
  '''
  author_string = ['%s (%s)' % (a['name'], a['email']) for a in authors]
  author_string = author_string.__str__()
  author_string = author_string.replace(',', ' and')[2:][:-2]
  return 'Copyright (c) %s by %s' % (year, author_string)
get_wrapped_text()
def sylva.code_generation.mit_license.get_wrapped_text (lic_title = lic_title, contact = get_contact(year, authors), permission = permission, permission_extra = permission_extra, final = final, width = 80, comment_perfix = '#', indention_size = 2)
Definition at line 76 of file mit_license.py.
Referenced by sylva.code_generation.mit_license.get_contact(), sylva.code_generation.mit_license.python(), and sylva.code_generation.mit_license.vhdl().
  indention_size = 2) :
  comment_length = len(comment_perfix)
  result = ''
  lic_title = textwrap.wrap(lic_title, width - comment_length - 2)
  for line in lic_title :
    result += comment_perfix + ' ' + line + '\n'
  for section in [contact, permission, permission_extra, final] :
    section = textwrap.wrap(section, width - comment_length - indention_size - 2)
    result += '\n'
    for line in section :
      result += ' ' * indention_size + comment_perfix + ' ' + line + '\n'
  return result[:-1]
python()
def sylva.code_generation.mit_license.python (year = year, authors = authors, width = width, indention_size = python_indention_size)
Definition at line 100 of file mit_license.py.
References sylva.code_generation.mit_license.get_contact(), and sylva.code_generation.mit_license.get_wrapped_text().
def python(year = year, authors = authors, width = width, indention_size = python_indention_size) :
  return get_wrapped_text(width = width,
                           contact = get_contact(year, authors),
                           comment_perfix = '#',
                           indention_size = indention_size)
vhdl()
def sylva.code_generation.mit_license.vhdl (year = year, authors = authors, width = width, indention_size = vhdl_indention_size)
Definition at line 94 of file mit_license.py.
References sylva.code_generation.mit_license.get_contact(), and sylva.code_generation.mit_license.get_wrapped_text().
def vhdl(year = year, authors = authors, width = width, indention_size = vhdl_indention_size) :
  return get_wrapped_text(width = width,
                           contact = get_contact(year, authors),
                           comment_perfix = '--',
                           indention_size = indention_size)
Variable Documentation
__author__
string sylva.code_generation.mit_license.__author__ = 'Shuo Li <contact@shuol.li>' [private]
Definition at line 24 of file mit_license.py.
__version__
string sylva.code_generation.mit_license.__version__ = '2014-06-12-11:43' [private]
Definition at line 25 of file mit_license.py.
authors
list sylva.code_generation.mit_license.authors = [ {'name': 'Shuo Li', 'email': 'contact@shuo.li'} ]
Definition at line 29 of file mit_license.py.
final
string sylva.code_generation.mit_license.final = 'THE SOFTWARE IS PROVIDED `AS IS`, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.'
Definition at line 43 of file mit_license.py.
lic_title
string sylva.code_generation.mit_license.lic_title = 'The MIT License (MIT)'
Definition at line 37 of file mit_license.py.
permission
string sylva.code_generation.mit_license.permission = 'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the `Software`), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:'
Definition at line 39 of file mit_license.py.
permission_extra
string sylva.code_generation.mit_license.permission_extra = 'The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.'
Definition at line 41 of file mit_license.py.
python_indention_size
int sylva.code_generation.mit_license.python_indention_size = 2
Definition at line 33 of file mit_license.py.
vhdl_indention_size
int sylva.code_generation.mit_license.vhdl_indention_size = 3
Definition at line 32 of file mit_license.py.
width
int sylva.code_generation.mit_license.width = 80
Definition at line 31 of file mit_license.py.
year
sylva.code_generation.mit_license.year = time.strftime('%Y', time.localtime())
Definition at line 28 of file mit_license.py.