sylva.base.fimp Namespace Reference
Classes
class fimp
class fimp_lib
class fimp_set
Functions
def assign_to (self, one_fimp)
def add_fimp (self, fimp)
def generate_random_fimps (fimp_name, num_fimps=8, max_area=0, max_width=4, max_height=4, min_area=0, min_width=1, min_height=1, max_computation=20, max_input=10, max_output=10, min_computation=2, min_input=1, min_output=1, max_energy=10, min_energy=1)
def load_fimp (fimp_dict, load_actors=False, actors=[])
def load_fimp_set (fimp_dict)
def load_fimp_lib (fimp_dict)
def load_from_file (filename)
Variables
assign_to
add_fimp
Function Documentation
add_fimp()
def sylva.base.fimp.add_fimp (self, fimp)
  Add one FIMP instance to the CGRA fabric.
  XY location may or may not to be presented in the FIMP instance.
Definition at line 196 of file fimp.py.
References sylva.base.fimp.add_fimp.
  def add_fimp(self, fimp) :
    '''
      Add one FIMP instance to the CGRA fabric.
      XY location may or may not to be presented in the FIMP instance.
    '''
    if fimp not in self.fimps :
      self.fimps.append(fimp)
assign_to()
def sylva.base.fimp.assign_to (self, one_fimp)
  Assign a FIMP instance to execute this HSDF actor.
Definition at line 182 of file fimp.py.
References sylva.base.fimp.assign_to.
  def assign_to(self, one_fimp) :
    '''
      Assign a FIMP instance to execute this HSDF actor.
    '''
    one_fimp.add_actor(self)
generate_random_fimps()
def sylva.base.fimp.generate_random_fimps (fimp_name, num_fimps = 8, max_area = 0, max_width = 4, max_height = 4, min_area = 0, min_width = 1, min_height = 1, max_computation = 20, max_input = 10, max_output = 10, min_computation = 2, min_input = 1, min_output = 1, max_energy = 10, min_energy = 1)
  Generate FIMP Instances for Testing
  -----------------------------------

  0. All ranges are inclusive

  1. fimp_name: string, the name of the function to be executed on the FIMP instances.
  2. num_fimps: integer, the number of FIMP instances to generate.
  3. max_width: integer, maximum width of the FIMP instances
  4. max_height: integer, maximum height of the FIMP instances
  5. min_width: integer, minimum width of the FIMP instances
  6. min_height: integer, minimum height of the FIMP instances
  7. max_computation: integer, maximum computation phase length
  8. max_input: integer, maximum input phase length
  9. max_output: integer, maximum output phase length
  10. min_computation: integer, minimum computation phase length
  11. min_input: integer, minimum input phase length
  12. min_output: integer, minimum output phase length
Definition at line 217 of file fimp.py.
    max_energy = 10, min_energy = 1) :
    '''
      Generate FIMP Instances for Testing
      -----------------------------------
      0. All ranges are inclusive
      1. fimp_name: string, the name of the function to be executed on the FIMP instances.
      2. num_fimps: integer, the number of FIMP instances to generate.
      3. max_width: integer, maximum width of the FIMP instances
      4. max_height: integer, maximum height of the FIMP instances
      5. min_width: integer, minimum width of the FIMP instances
      6. min_height: integer, minimum height of the FIMP instances
      7. max_computation: integer, maximum computation phase length
      8. max_input: integer, maximum input phase length
      9. max_output: integer, maximum output phase length
      10. min_computation: integer, minimum computation phase length
      11. min_input: integer, minimum input phase length
      12. min_output: integer, minimum output phase length
    '''
    # input phase can last as long as the computation phase
    if max_input > max_computation:
      max_input = max_computation
    # output phase can last as long as the computation phase
    if max_output > max_computation:
      max_output = max_computation
    fimps = []
    for x in range(num_fimps):
      computation_phase = random.randint(min_computation, max_computation)
      ratio = computation_phase/ (max_computation + min_computation)
      if (max_input > computation_phase):
        input_max = computation_phase
      else :
        input_max = max_input
      if (min_input > computation_phase):
        input_min = computation_phase
      else :
        input_min = min_input
      if (max_output > computation_phase):
        output_max = computation_phase
      else :
        output_max = max_output
      if (min_output > computation_phase):
        output_min = computation_phase
      else :
        output_min = min_output
      input_phase = random.randint(input_min, input_max)
      output_phase = random.randint(output_min, output_max)
      width = random.randint(min_width, max_width)
      width = int((ratio * (max_width + min_width) + width)/2)
      #================================================
      # expected value + random value
      # Actual value = -----------------------------
      # 2
      #================================================
      height = random.randint(min_height, max_height)
      height = int((ratio * (max_height + min_height) + height)/2)
      if max_area != 0 :
        area = random.randint(min_area, max_area)
        area = int((ratio * (max_area + min_area) + area)/2)
      else :
        area = width * height
      energy = random.randint(min_energy, max_energy)
      energy = int((ratio * (max_energy + min_energy) + energy)/2)
      fimps.append(
        fimp(name = fimp_name, type = x,
              area = area,
              width = width,
              height = height,
              energy = energy,
              computation_phase = computation_phase,
              input_phase = input_phase,
              output_phase = output_phase))
    return fimps
load_fimp()
def sylva.base.fimp.load_fimp (fimp_dict, load_actors = False, actors = [])
Definition at line 500 of file fimp.py.
Referenced by sylva.base.fimp.load_fimp_set(), and sylva.base.fimp.load_from_file().
def load_fimp(fimp_dict, load_actors = False, actors = []) :
  width = 0
  height = 0
  if 'width' in fimp_dict.keys() and 'height' in fimp_dict.keys():
    width = int(fimp_dict['width'])
    height = int(fimp_dict['height'])
    area = width * height
  else :
    area = int(fimp_dict['area'])
  result = fimp(
    name = str(fimp_dict['name']),
    type = int(fimp_dict['type']),
    area = area,
    width = width,
    height = height,
    energy = int(fimp_dict['energy']),
    computation_phase = int(fimp_dict['computation_phase']),
    input_phase = int(fimp_dict['input_phase']),
    output_phase = int(fimp_dict['output_phase']))
  if 'index' in fimp_dict.keys():
    result.index = int(fimp_dict['index'])
  if 'extra_buffer' in fimp_dict.keys() :
    result.extra_buffer = int(fimp_dict['extra_buffer'])
  if load_actors == False :
    return result
  else :
    result.actors = [ actors[i] for i in fimp_dict['actors'] ]
    return result
load_fimp_lib()
def sylva.base.fimp.load_fimp_lib (fimp_dict)
Definition at line 546 of file fimp.py.
References sylva.base.fimp.load_fimp_set().
Referenced by sylva.base.fimp.load_from_file().
def load_fimp_lib(fimp_dict) :
  architecture = str(fimp_dict['architecture'])
  name = str(fimp_dict['name'])
  functions = fimp_dict['functions']
  result = fimp_lib(architecture, name)
  for f in functions :
    result.add_fimp_set(load_fimp_set(fimp_dict[str(f)]))
  return result
load_fimp_set()
def sylva.base.fimp.load_fimp_set (fimp_dict)
Definition at line 535 of file fimp.py.
References sylva.base.fimp.load_fimp().
Referenced by sylva.base.fimp.load_fimp_lib(), and sylva.base.fimp.load_from_file().
def load_fimp_set(fimp_dict) :
  result = fimp_set(name = str(fimp_dict['name']))
  types = fimp_dict['types']
  for t in types :
    result.add_fimp(load_fimp(fimp_dict[str(t)]))
  result.generics = fimp_dict['generics']
  result.input_ports = fimp_dict['input_ports']
  result.output_ports = fimp_dict['output_ports']
  return result
load_from_file()
def sylva.base.fimp.load_from_file (filename)
Definition at line 559 of file fimp.py.
References sylva.base.fimp.load_fimp(), sylva.base.fimp.load_fimp_lib(), and sylva.base.fimp.load_fimp_set().
def load_from_file(filename) :
  f = open(filename, 'r')
  s = f.read()
  f.close()
  d = json.loads(s)
  if 'architecture' in d.keys() :
    return load_fimp_lib(d)
  if 'types' in d.keys() :
    return load_fimp_set(d)
  if 'name' in d.keys() :
    return load_fimp(d)
  return None
Variable Documentation
add_fimp
sylva.base.fimp.add_fimp
Definition at line 206 of file fimp.py.
Referenced by sylva.base.fimp.add_fimp().
assign_to
sylva.base.fimp.assign_to
Definition at line 190 of file fimp.py.
Referenced by sylva.base.fimp.assign_to().