sylva.base.sdf Namespace Reference
All SDF graph related classes and methods.
Classes
class actor
class DataTokenType
Class for data token type.
class edge
class Port
Class for port.
class sdfg
Functions
def load_sdf_port (json_dict)
def load_sdf_edge_index (json_dict)
def load_sdf_edge (json_dict, actors)
def create_sdf_edge (src_actor_index, src_port_index, dest_actor_index, dest_port_index, actors)
def connect (src_actor, src_port_index, src_data_token_count, dest_actor, dest_port_index, dest_data_token_count, data_token_type=DataTokenType('noName', 1))
def load_sdf_actor (json_dict, keys=[])
def make_sdf_actor (name, index, inports, outports, input_token_type=[DataTokenType('std_logic', 1)], output_token_type=[DataTokenType('std_logic', 1)])
def serialize_sdf_graph (actors, edges)
def load_sdf_graph (json_dict, actor_keys=[])
def dump_to_file (item, filepath, indent=2)
def add_actor (actors, name, index, inports, outports, input_token_type=[DataTokenType('std_logic', 1)], output_token_type=[DataTokenType('std_logic', 1)])
def add_edge (edges, src_actor_index, src_port_index, dest_actor_index, dest_port_index, actors)
def get_layered_actors (actors)
Variables
string __author__ = 'Shuo Li <contact@shuol.li>'
string __version__ = '2017-05-12'
string __license__ = 'MIT'
d = DataTokenType()
dc = dict(d)
dictionary default_actor_style
dictionary default_annotation_style
Detailed Description
All SDF graph related classes and methods.
Function Documentation
add_actor()
def sylva.base.sdf.add_actor (actors, name, index, inports, outports, input_token_type = [DataTokenType('std_logic', 1)], output_token_type = [DataTokenType('std_logic', 1)])
Definition at line 393 of file sdf.py.
References sylva.base.sdf.add_edge(), and sylva.base.sdf.make_sdf_actor().
Referenced by sylva.dse.dse_engine_v1.assign_fimps(), and sylva.base.sdf.dump_to_file().
                  output_token_type=[DataTokenType('std_logic', 1)]):
        actors.append(make_sdf_actor(name, index,
                                     inports, outports, input_token_type, output_token_type))
add_edge()
def sylva.base.sdf.add_edge (edges, src_actor_index, src_port_index, dest_actor_index, dest_port_index, actors)
Definition at line 399 of file sdf.py.
References sylva.base.sdf.create_sdf_edge().
Referenced by sylva.base.sdf.add_actor().
                 dest_actor_index, dest_port_index, actors):
        return edges.append(create_sdf_edge(
            src_actor_index, src_port_index,
            dest_actor_index, dest_port_index, actors))
connect()
def sylva.base.sdf.connect (src_actor, src_port_index, src_data_token_count, dest_actor, dest_port_index, dest_data_token_count, data_token_type = DataTokenType('noName', 1))
  Create a connection between two ports of two actors.
  Ports are automatically generated.
Definition at line 247 of file sdf.py.
Referenced by sylva.base.sdf.create_sdf_edge().
                data_token_type=DataTokenType('noName', 1)):
        '''
          Create a connection between two ports of two actors.
          Ports are automatically generated.
        '''
        src_ports = [output_port
                     for output_port in src_actor.output_ports
                     if output_port.index == src_port_index]
        if len(src_ports) == 1:
            src_port = src_ports[0]
        else:
            src_port = port(name='%s_output_port_%d'
                            % (src_actor.name, src_port_index),
                            index=src_port_index,
                            type=data_token_type,
                            count=src_data_token_count)
        dest_ports = [input_port
                      for input_port in dest_actor.input_ports
                      if input_port.index == dest_port_index]
        if len(dest_ports) == 1:
            dest_port = dest_ports[0]
        else:
            dest_port = port(name='%s_input_port_%d'
                             % (dest_actor.name, dest_port_index),
                             index=dest_port_index,
                             type=data_token_type,
                             count=dest_data_token_count)
        return edge(src_actor, src_port, dest_actor, dest_port)
create_sdf_edge()
def sylva.base.sdf.create_sdf_edge (src_actor_index, src_port_index, dest_actor_index, dest_port_index, actors)
Definition at line 235 of file sdf.py.
References sylva.base.sdf.connect().
Referenced by sylva.base.sdf.add_edge(), and sylva.base.sdf.load_sdf_edge().
                        dest_actor_index, dest_port_index, actors):
        src_actor = actors[src_actor_index]
        src_port = src_actor.output_ports[src_port_index]
        dest_actor = actors[dest_actor_index]
        dest_port = dest_actor.input_ports[dest_port_index]
        return edge(src_actor, src_port, dest_actor, dest_port)
dump_to_file()
def sylva.base.sdf.dump_to_file (item, filepath, indent = 2)
Definition at line 386 of file sdf.py.
References sylva.base.sdf.add_actor().
    def dump_to_file(item, filepath, indent=2):
        f = open(filepath, 'w+')
        f.write(json.dumps(item, indent=2))
        f.close()
get_layered_actors()
def sylva.base.sdf.get_layered_actors (actors)
Definition at line 428 of file sdf.py.
Referenced by sylva.base.sdf.sdfg.layered_actors().
    def get_layered_actors(actors):
        result = []
        checked = []
        while not result or result[-1]:
            result.append([])
            for a in actors:
                if a not in checked:
                    if not a.previous:
                        result[-1].append(a)
                        continue
                    else:
                        for pa in a.previous:
                            if pa.src_actor in checked:
                                if a not in result[-1]:
                                    result[-1].append(a)
            checked += result[-1]
        return result[:-1]
load_sdf_actor()
def sylva.base.sdf.load_sdf_actor (json_dict, keys = [])
Definition at line 334 of file sdf.py.
References sylva.base.sdf.load_sdf_edge_index(), sylva.base.sdf.load_sdf_port(), and sylva.base.sdf.make_sdf_actor().
Referenced by sylva.base.sdf.load_sdf_graph().
    def load_sdf_actor(json_dict, keys=[]):
        result = actor(name=str(json_dict['name']),
                       index=int(json_dict['index']),
                       input_ports=[load_sdf_port(p)
                                    for p in json_dict['input_ports']],
                       output_ports=[load_sdf_port(p)
                                     for p in json_dict['output_ports']],
                       next=[load_sdf_edge_index(e)
                             for e in json_dict['next']],
                       previous=[load_sdf_edge_index(e)
                                 for e in json_dict['previous']])
        actor_keys = keys or [
            'input_end', 'output_start',
            'buffer_end', 'start', 'end',
            'base_actor_index', 'fimp_index']
        for key in actor_keys:
            if key in json_dict.keys():
                setattr(result, key, json_dict[key])
        return result
load_sdf_edge()
def sylva.base.sdf.load_sdf_edge (json_dict, actors)
Definition at line 222 of file sdf.py.
References sylva.base.sdf.create_sdf_edge(), and sylva.base.sdf.load_sdf_edge_index().
Referenced by sylva.base.sdf.load_sdf_graph().
    def load_sdf_edge(json_dict, actors):
        src_actor_index, src_port_index, dest_actor_index, dest_port_index =
      load_sdf_edge_index(json_dict)
        src_actor = actors[src_actor_index]
        src_port = src_actor.output_ports[src_port_index]
        dest_actor = actors[dest_actor_index]
        dest_port = dest_actor.input_ports[dest_port_index]
        return edge(src_actor, src_port, dest_actor, dest_port)
load_sdf_edge_index()
def sylva.base.sdf.load_sdf_edge_index (json_dict)
Definition at line 212 of file sdf.py.
Referenced by sylva.base.sdf.load_sdf_actor(), and sylva.base.sdf.load_sdf_edge().
    def load_sdf_edge_index(json_dict):
        src_actor_index = int(json_dict['src_actor'])
        src_port_index = int(json_dict['src_port'])
        dest_actor_index = int(json_dict['dest_actor'])
        dest_port_index = int(json_dict['dest_port'])
        return (src_actor_index, src_port_index, dest_actor_index, dest_port_index)
load_sdf_graph()
def sylva.base.sdf.load_sdf_graph (json_dict, actor_keys = [])
Definition at line 379 of file sdf.py.
References sylva.base.sdf.load_sdf_actor(), and sylva.base.sdf.load_sdf_edge().
Referenced by sylva.base.sdf.sdfg.load().
    def load_sdf_graph(json_dict, actor_keys=[]):
        actors = []
        edges = []
        actors = [load_sdf_actor(a, actor_keys) for a in json_dict['actors']]
        edges = [load_sdf_edge(e, actors) for e in json_dict['edges']]
        return (actors, edges)
load_sdf_port()
def sylva.base.sdf.load_sdf_port (json_dict)
Definition at line 166 of file sdf.py.
Referenced by sylva.base.sdf.load_sdf_actor().
def load_sdf_port(json_dict):
    return Port(name=str(json_dict['name']),
                index=int(json_dict['index']),
                type=DataTokenType.deserialize(json_dict['type']),
                count=int(json_dict['count']))
make_sdf_actor()
def sylva.base.sdf.make_sdf_actor (name, index, inports, outports, input_token_type = [DataTokenType('std_logic', 1)], output_token_type = [DataTokenType('std_logic', 1)])
Definition at line 359 of file sdf.py.
Referenced by sylva.base.sdf.add_actor(), and sylva.base.sdf.load_sdf_actor().
                       output_token_type=[DataTokenType('std_logic', 1)]):
        input_ports = [Port('%s_in_%s' % (name, i), i,
                            input_token_type[i], c)
                       for i, c in enumerate(inports)]
        output_ports = [Port('%s_out_%s' % (name, i), i,
                             output_token_type[i], c)
                        for i, c in enumerate(outports)]
        return actor(name=name, index=index,
                     input_ports=input_ports, output_ports=output_ports)
serialize_sdf_graph()
def sylva.base.sdf.serialize_sdf_graph (actors, edges)
Definition at line 373 of file sdf.py.
    def serialize_sdf_graph(actors, edges):
        result = {}
        result['actors'] = [actor.serialize() for actor in actors]
        result['edges'] = [edge.serialize() for edge in edges]
        return result
Variable Documentation
__author__
string sylva.base.sdf.__author__ = 'Shuo Li <contact@shuol.li>' [private]
Definition at line 12 of file sdf.py.
__license__
string sylva.base.sdf.__license__ = 'MIT' [private]
Definition at line 14 of file sdf.py.
__version__
string sylva.base.sdf.__version__ = '2017-05-12' [private]
Definition at line 13 of file sdf.py.
d
sylva.base.sdf.d = DataTokenType()
Definition at line 74 of file sdf.py.
dc
sylva.base.sdf.dc = dict(d)
Definition at line 75 of file sdf.py.
default_actor_style
dictionary sylva.base.sdf.default_actor_style
Initial value:
= {
        'node_shape': 'circle',
        'facecolor': 'white',
        'edgecolor': 'black',
        'linestyle': 'solid',
        'linewidth': 1,
        'radius': 0.4,
        'width': 0.4,
        'height': 0.4,
        'margin': 0.8,
    }
Definition at line 407 of file sdf.py.
default_annotation_style
dictionary sylva.base.sdf.default_annotation_style
Initial value:
= {
        'color': 'black',
        'fontweight': 'normal',
        'fontsize': 12,
        'ha': 'center',
        'va': 'center'}
Definition at line 419 of file sdf.py.