sylva.dse.dse_engine_v1 Namespace Reference
Classes
class dse_v1
Functions
def approximate_numbers (number)
def most_parallel_schedule (p, i, c, a)
def ceil_in_list (ordered_number_list, number)
def all_schedules (sdf_actors, sdf_edges)
def some_schedules (sdf_actors, sdf_edges, size=None)
def schedules (p, a, i, result=[])
def assign_fimps (hsdf_actors, fimp_count_list)
Variables
string __author__ = 'Shuo Li <contact@shuol.li>'
string __version__ = '2014-05-09-11:25'
Function Documentation
all_schedules()
def sylva.dse.dse_engine_v1.all_schedules (sdf_actors, sdf_edges)
  Find all load balanced schedules for a given SDF graph.
Definition at line 385 of file dse_engine_v1.py.
References sylva.dse.dse_engine_v1.approximate_numbers(), sylva.base.sdf_to_hsdf.get_repetition_count(), and sylva.dse.dse_engine_v1.schedules().
Referenced by sylva.dse.dse.search_all(), and sylva.dse.dse_engine_v1.some_schedules().
def all_schedules((sdf_actors, sdf_edges)) :
  '''
    Find all load balanced schedules for a given SDF graph.
  '''
  p = get_repetition_count((sdf_actors, sdf_edges))
  a = [ approximate_numbers(n) for n in p ]
  result = []
  for s in sdf_actors :
    result = schedules(p, a, s.index, result)
  return result
approximate_numbers()
def sylva.dse.dse_engine_v1.approximate_numbers (number)
  Return all approximate numbers of an input number as a list.
  Complicity = O{n}
  Good enough for small scale problems.
Definition at line 340 of file dse_engine_v1.py.
Referenced by sylva.dse.dse_engine_v1.all_schedules(), and sylva.dse.dse_engine_v1.some_schedules().
def approximate_numbers(number) :
  '''
    Return all approximate numbers of an input number as a list.
    Complicity = O{n}
    Good enough for small scale problems.
  '''
  return [ i for i in xrange(1, int(number) + 1)
           if int(number) % i == 0 ]
assign_fimps()
def sylva.dse.dse_engine_v1.assign_fimps (hsdf_actors, fimp_count_list)
  Create a relative schedule based on a given FIMP count list.
Definition at line 429 of file dse_engine_v1.py.
References sylva.base.sdf.add_actor().
Referenced by sylva.dse.dse.search_all().
def assign_fimps(hsdf_actors, fimp_count_list) :
  '''
    Create a relative schedule based on a given FIMP count list.
  '''
  actors = {}
  for a in hsdf_actors :
    if a.base_actor.index not in actors.keys() :
      actors[a.base_actor.index] = []
    actors[a.base_actor.index].append(a)
  fimps = [ fimp(index = i)
            for i in xrange(sum(fimp_count_list)) ]
  c = 0
  # current FIMP index
  for i in actors.keys() : # for each SDF actor
    f = 0
    # current FIMP index for one SDF actor
    for a in actors[i] :
    # for each HSDF actor
      if f == fimp_count_list[i] :
        c -= fimp_count_list[i]
        f = 0
      fimps[c].name = a.name
      fimps[c].add_actor(a)
      c += 1
      f += 1
  return fimps
ceil_in_list()
def sylva.dse.dse_engine_v1.ceil_in_list (ordered_number_list, number)
  Ceiling a given number in a given ordered number list.
Definition at line 373 of file dse_engine_v1.py.
Referenced by sylva.dse.dse_engine_v1.most_parallel_schedule().
def ceil_in_list(ordered_number_list, number) :
  '''
    Ceiling a given number in a given ordered number list.
  '''
  for i, v in enumerate(ordered_number_list) :
    if number <= v :
      return v
  return ordered_number_list[-1]
most_parallel_schedule()
def sylva.dse.dse_engine_v1.most_parallel_schedule (p, i, c, a)
  Find the most parallel schedule
  when the amount of used FIMPs (c)
  for an SDF actor with index (i) is given

  ---

  p: repetition vector
  i: SDF actor index
  c: FIMP count for SDF actor i
  a: approximate numbers for p
Definition at line 351 of file dse_engine_v1.py.
References sylva.dse.dse_engine_v1.ceil_in_list().
Referenced by sylva.dse.dse_engine_v1.schedules().
def most_parallel_schedule(p, i, c, a) :
  '''
    Find the most parallel schedule
    when the amount of used FIMPs (c)
    for an SDF actor with index (i) is given
    ---
    p: repetition vector
    i: SDF actor index
    c: FIMP count for SDF actor i
    a: approximate numbers for p
  '''
  ratio = int(p[i] / c)
  # ratio is always integer
  # since c is always one element of p[i]
  return [ ceil_in_list(a[index], int(p[index]/ratio))
           for index in xrange(len(p)) ]
schedules()
def sylva.dse.dse_engine_v1.schedules (p, a, i, result = [])
Definition at line 422 of file dse_engine_v1.py.
References sylva.dse.dse_engine_v1.most_parallel_schedule().
Referenced by sylva.dse.dse_engine_v1.all_schedules(), and sylva.dse.dse_engine_v1.some_schedules().
def schedules(p, a, i, result = []) :
  for c in a[i] :
    schedule = most_parallel_schedule(p, i, c, a)
    if schedule not in result :
      result.append(schedule)
  return result
some_schedules()
def sylva.dse.dse_engine_v1.some_schedules (sdf_actors, sdf_edges, size = None)
  Find a subset of all load balanced schedules for a given SDF graph.
Definition at line 399 of file dse_engine_v1.py.
References sylva.dse.dse_engine_v1.all_schedules(), sylva.dse.dse_engine_v1.approximate_numbers(), sylva.misc.util.evenly_pick(), sylva.base.sdf_to_hsdf.get_repetition_count(), and sylva.dse.dse_engine_v1.schedules().
Referenced by sylva.dse.dse.search_all().
def some_schedules((sdf_actors, sdf_edges), size = None) :
  '''
    Find a subset of all load balanced schedules for a given SDF graph.
  '''
  if not size :
    return all_schedules((sdf_actors, sdf_edges))
  p = get_repetition_count((sdf_actors, sdf_edges))
  a = [ approximate_numbers(n) for n in p ]
  p_sorted = sorted([ (k, v) for k, v in enumerate(p)], key = lambda x : x[1], reverse = True)
  result = []
  if len(a[p_sorted[0][0]]) < size :
    for (k, v) in p_sorted :
      result = schedules(p, a, k, result)
      if len(result) >= size :
        return result [:size]
    return result
  return evenly_pick(schedules(p, a, p[0][0], result), size)
Variable Documentation
__author__
string sylva.dse.dse_engine_v1.__author__ = 'Shuo Li <contact@shuol.li>' [private]
Definition at line 23 of file dse_engine_v1.py.
__version__
string sylva.dse.dse_engine_v1.__version__ = '2014-05-09-11:25' [private]
Definition at line 24 of file dse_engine_v1.py.